### ISSUE TITLE
Skipping source fields/methods

### ISSUE THREAD

**Issue by LordPinhead** [modelmapper/modelmapper#158]
Hi,
is just finished with my first testing of modelmapper and found a strange behavior with no bug or solution somerwhere else. 

My Parent Bean has an final Method getId() which comes from Source should be skipped because it´s DB metadata. But i´ve got an Exception when i try it:

``` java
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Cannot map final method test.DBBean.getId().

2) A mapping is missing a required destination member.
```

Lets show it with some testcode:

``` java
class DBBean {
    private int id;
    public final int getId() {
        return this.id;
    }
    public void setId(int id) {
        this.id = id;
    }
}

class Source extends DBBean {
    private String name = null;
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
         this.name = name;
    }
}

class Destination {
    private String name = null;
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
}

class SourceMapper {
    public Destination Map() {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.addMappings(new SourcePropertyMap());
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.LOOSE);
        modelMapper.validate(); // with and without, it wont work
        return modelMapper.map(source, Destination.class);
    }
}
public class SourcePropertyMap extends PropertyMap<Source, Destination> {
    protected void configure() {
        map().setName(source.getName()); // use the name
        skip(source.getId()); // skip the metadata fields from source
    }
}
public class testMap {
    @Test
    public void testMapping() {
        SourceMapper mapper = new SourceMapper();
        Source source = new Source();
        source.setId(1);
        source.setName("Test");
        Destination destination = mapper.Map(source);
    }
}
```

With or without modelMapper.validate(), i crashes.
Ok, kicking the final out in my DBBean Class, the first error vanishes, but the second error (A mapping is missing a required destination member.)  still appears.

I have 1 field skipped and 1 field mapped, but it wont work. The automatic mapping works, but is no option for my production code with different namings, already gave it a try.

If someone now a solution, i would be happy to see it, meanwhile the search must go on :)

Edit:
Ok, found one mistake, i have NPE in a condition, but i have still the issue when i keep the final statement in my code.
Maybe the automatic mapping is trying to map the id to some similar fields in the Destination Bean, i still have 50 not filled.

**Comment by LordPinhead** [comment]
Found the next Problem.

Lets assume in Source i have an Array/Property which has to be converted to another Array. 
So i update my PropertyMap Class, add my Converter and use it - and it crashes.

Updated Testclasses:

```java
public class Source extends DBBean {
	 private String name = null;
	 private String deeperName = null;
	 
   public String getName() {
       return this.name;
   }
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getDeeperName() {
		return this.deeperName;
	}

	public void setDeeperName(String deeperName) {
		this.deeperName = deeperName;
	}

}

public class Destination {
    private String name = null;
  
    private DeeperDestination[] deeperDestination;

    public DeeperDestination[] getDeeperDestination() {
        return this.deeperDestination;
    }
  
    public void setDeeperDestination(DeeperDestination[] deeperDestination) {
        this.deeperDestination = deeperDestination;
    }
  
    public String getName() {
        return this.name;
    }
	
    public void setName(String name) {
        this.name = name;
    }
}

public class DeeperDestination {
    private long id;
    private String name;
    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public class SourcePropertyMap extends PropertyMap<Source, Destination> {
    protected void configure() {
        map().setName(source.getName());
        using(Source2DeeperArray).map(source).setDeeperDestination(null);
    }

    Converter<Source, DeeperDestination[]> Source2DeeperArray = new AbstractConverter<Source, DeeperDestination[]>() {
        protected DeeperDestination[] convert(Source source) {

            DeeperDestination[] dest = new DeeperDestination[1];
            dest[0] = new DeeperDestination();
            dest[0].setName(source.getDeeperName());

            return dest;
        }
    };
}

    @Test
    public void testMapping() {
        SourceMapper mapper = new SourceMapper();
        Source source = new Source();
        source.setId(1);
        source.setName("Test");
        source.setDeeperName("TestDeeper");
        
        Destination dest = mapper.Map(source);
        
        assertThat(dest.getName(), is("Test"));
        assertThat(dest.getDeeperDestination(), is(not(nullValue())));
        assertThat(dest.getDeeperDestination()[0].getName(), is("TestDeeper"));
    }
```

So my premise is, the name in Destination is "Test" and in the first DeeperDestination Object, the name is "TestDeeper".

Crashing with the following Stacktrace:

```java
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to configure mappings

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:207)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
	at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
	at de.modelmapper.test.SourceMapper.Map(SourceMapper.java:30)
	at de.modelmapper.test.testMap.testMapping(testMap.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException
	at java.lang.reflect.Array.multiNewArray(Native Method)
	at java.lang.reflect.Array.newInstance(Array.java:108)
	at org.modelmapper.internal.util.Primitives.primitiveFor(Primitives.java:144)
	at org.modelmapper.internal.ExplicitMappingVisitor.methodFor(ExplicitMappingVisitor.java:337)
	at org.modelmapper.internal.ExplicitMappingVisitor.access$600(ExplicitMappingVisitor.java:33)
	at org.modelmapper.internal.ExplicitMappingVisitor$MappingCapturingVisitor.visitEnd(ExplicitMappingVisitor.java:203)
	at org.modelmapper.internal.asm.ClassReader.b(Unknown Source)
	at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
	at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:222)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
	... 28 more
```

In Primitives.java it creates an NPE at:
```java
case Type.ARRAY:
        return Array.newInstance(primitiveFor(type.getElementType()), new int[type.getDimensions()])
            .getClass(); 
...
  public static Class<?> primitiveFor(Class<?> wrapper) {
    return wrapperToPrimitive.get(wrapper);
  }

Properties of Type:
argumentTypes	Type[1]  (id=1110)	
	[0]	Type  (id=1112)	
		a	9	
		b	[Lde/modelmapper/test/DeeperDestination; (id=1117)	
		c	1	
		d	39	
```

I can´t create an testcase for this part and for Type because its not visible. Maybe the author knows more.

**Comment by chhsiao90** [comment]
For the first comment, I think there is no need to skip the source field, and after remove the line, I think it should work.

And I can't reproduce for your second comment, please try our latest release and check if the issue is still reproducible.
