### ISSUE TITLE
Exception thrown when trying to add mapping when classes are compiled with jdk8 named parameters

### ISSUE THREAD

**Issue by knes1** [modelmapper/modelmapper#162]
ModelMapper seems to be throwing exceptions when trying to register mappings when following conditions are satisfied:
- Classes are compiled with jdk8 named parameters support (-parameters argument to javac)
- Destination class implements an interface (such as Comparable)

Here's a test case that fails when compiled with -parameters option:

```
public class ModelMapperTest {

    @Test
    public void testModelMapper() {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.addMappings(new TestDTOMapping());
        Model model = new Model();
        modelMapper.map(new ModelDto("test"), model);
        Assert.assertEquals("test", model.getTest());
    }

    public static class Model implements Comparable<Model> {
        private String test;

        public String getTest() {
            return test;
        }

        public void setTest(String test) {
            this.test = test;
        }

        @Override
        public int compareTo(Model o) {
            return test.compareTo(o.test);
        }
    }

    public static class ModelDto {
        private String testDTO;

        public ModelDto(String testDTO) {
            this.testDTO = testDTO;
        }

        public String getTestDTO() {
            return testDTO;
        }

        public void setTestDTO(String testDTO) {
            this.testDTO = testDTO;
        }
    }

    public static class TestDTOMapping extends PropertyMap<ModelDto, Model> {

        @Override
        protected void configure() {
            map(source.getTestDTO(), destination.getTest());
        }
    }
}
```

You can clone test case from here: https://github.com/knes1/modelmapper-test
(after cloning the repo just run `mvn clean test` - project is configured to be compiled with named parameters support)

When running this testcase I receive following error:

```
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Failed to generate proxy class for io.github.knes1.modelmappertest.ModelMapperTest$Model. Ensure that io.github.knes1.modelmappertest.ModelMapperTest$Model has a non-private constructor.
Caused by: java.lang.RuntimeException
    at org.modelmapper.internal.asm.MethodVisitor.visitParameter(Unknown Source)
    at org.modelmapper.internal.asm.ClassReader.b(Unknown Source)
    at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
    at org.modelmapper.internal.asm.ClassReader.accept(Unknown Source)
    at org.modelmapper.internal.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
    at org.modelmapper.internal.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
    at org.modelmapper.internal.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
    at org.modelmapper.internal.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
    at org.modelmapper.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
    at org.modelmapper.internal.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
    at org.modelmapper.internal.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
    at org.modelmapper.internal.ProxyFactory.proxyClassFor(ProxyFactory.java:68)
    at org.modelmapper.internal.ProxyFactory.proxyFor(ProxyFactory.java:83)
    at org.modelmapper.internal.ExplicitMappingBuilder.createProxy(ExplicitMappingBuilder.java:294)
    at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:248)
    at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:230)
    at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
    at io.github.knes1.modelmappertest.ModelMapperTest.testModelMapper(ModelMapperTest.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

2) Failed to configure mappings
Caused by: org.modelmapper.internal.ErrorsException
    at org.modelmapper.internal.Errors.toException(Errors.java:254)
    at org.modelmapper.internal.ProxyFactory.proxyClassFor(ProxyFactory.java:70)
    at org.modelmapper.internal.ProxyFactory.proxyFor(ProxyFactory.java:83)
    at org.modelmapper.internal.ExplicitMappingBuilder.createProxy(ExplicitMappingBuilder.java:294)
    at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:248)
    at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:230)
    at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
    at io.github.knes1.modelmappertest.ModelMapperTest.testModelMapper(ModelMapperTest.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

2 errors
```

**Comment by jhalterman** [comment]
Thanks for filing. This could be a problem with cglib, which would not be ideal.

@sameb @raphw - have you seen this before, where `Enhancer` behaves wierd on JDK 8 when compiling with the -parameter option?

**Comment by jhalterman** [comment]
It looks like we need a new CGlib release to try and get this fixed. Working on that...

**Comment by raphw** [comment]
Its an issue with old ASM versions that cannot parse the meta data. A new cglib release would help but I wonder if that is ever happening.

**Comment by jhalterman** [comment]
@raphw I figured as much. FWIW: I'd love to switch over to ByteBuddy, but I think I'd need it to be more modularized. Lots of great features, but for the limited set of features I need, it's a big distro to take in.

**Comment by raphw** [comment]
It is difficult to combine modularization and importing third-party dependencies such as asm. I understand that Byte Buddy is larger that cglib but if file size is an issue I guess that importing the required files is the best option in the first place.

**Comment by jhalterman** [comment]
@raphw I assume ASM would be part of ByteBuddy's core along with basic stuff like subclassing. There are a ton of other features though that could be, at least in theory, separate dependencies: android support, the agent, and I get the sense, a lot more.

**Comment by meetyg** [comment]
Hi,
Was version 3.2 of cglib ever added to modelmapper?
I have similar problems, with the same exception happening.

**Comment by jhalterman** [comment]
Just pushed 5933cf1215d5ac35cdce6ec83edf3787140ebde7 which should fix this. @meetyg are you able to try out the latest in master?

**Comment by meetyg** [comment]
Hi,
Thanks for the quick response.
Using the update didn't help.
We have some classes with private constructors (which we don't want to change).
I thought that using a provider/converter will help model mapper to create the class, but it doen't seem to work.
I wrote a little test to demonstrate my problem:
```
public class Main {
	public static void main(String[] args) {
		ModelMapper modelMapper = new ModelMapper();

		modelMapper.addMappings( 
			new PropertyMap<Source,Target>() {
					Provider<PrivateConstructor> provider = new AbstractProvider<PrivateConstructor>() {

						@Override
						protected PrivateConstructor get() {
							return PrivateConstructor.create();
						}
					};
					
					@Override
					protected void configure() {
						/*
							Unable to skip, map, or use provider.
							Uncomment one of the following to see the problem:
						*/
						
						
						//skip(source.Private, destination.Private);
						//skip(destination.Private);
						//map(source.Private, destination.Private);
						with(provider).map(source.Private, destination.Private);						
					}
			}
	);
	
		Target t = modelMapper.map(new Source(), Target.class);

	}
}


public class Source {
	PrivateConstructor Private = PrivateConstructor.create();
}

public class Target {
	PrivateConstructor Private;
}

public class PrivateConstructor {
	 private PrivateConstructor() {}
	 
	 public static PrivateConstructor create()
	 {
		 return new PrivateConstructor();
	 }
}
```
When I run this, we get an exception similar to what @knes1 got, about having a non-private constructor.
			
Am I doing something wrong? 
Your help is appreciated :-)

**Comment by raphw** [comment]
@meetyg Are you getting the same exception? This should be impossible if you properly updated your dependency. cglib now allows the parameters option which were not available for old API versions, the same error cannot happen if you updated correctly.

**Comment by bplies-IAS** [comment]
Experienced this problem with 0.7.5 exactly as reported.  Using javac -parameters and a class that implements `Comparable`.  Just updated to 1.1.2 and it works fine now.  May be able to mark this ticket as resolved.
