### ISSUE TITLE
Got an error when I try to map Enum to int

### ISSUE THREAD

**Issue by sunke** [modelmapper/modelmapper#180]
Hi,
I got a ModelMapper configuration error When I try to map an enum to int using the following code:
```
private ModelMapper modelMapper = new ModelMapper();
{
    modelMapper.addMappings(new PropertyMap<ASUser, User>() {
             protected void configure() {
                map().setResourceId(source.getId() != null ? source.getId().toString() : null);
                map().setLimitType(source.getLimitType().ordinal());
        }
    });
}
```

```
Caused by: org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Cannot map final method java.lang.Enum.ordinal().

1 error
    at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
    at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:229)
    at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
    at com.infor.scm.as.servlet.UserComponent.<init>(UserComponent.java:68)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
    ... 24 more
```

**Comment by corzar71** [comment]
I have the same issue, the problem is caused by the usage of _ordinal()_ method in **configure()**.
You can try to use a [converter](http://modelmapper.org/user-manual/converters/) as workaround.
