### ISSUE TITLE
Problems when deployed as war in an ear file in Websphere

### ISSUE THREAD

**Issue by robertfmurdock** [modelmapper/modelmapper#218]
This seems very similar to the Osgi issues I've read about on here, but I'm having trouble finding a resolution to this myself.

I'm getting a "java.lang.NoClassDefFoundError: org.modelmapper.internal.cglib.proxy.Factory" error when trying to use a model mapper as part of an old struts application deployed into Websphere.

I've attempted to fix this by:
 - adding "import-package" entries to the manifest file like this:

`
<Import-Package>
org.modelmapper.internal.cglib.proxy, org.modelmapper.internal.cglib.core, org.modelmapper.internal.cglib.transform
</Import-Package>
`
    
But that did not work, whether I applied this at the War Manifest or the Ear manifest.

Any suggestions welcome! My Websphere knowledge is pretty limited.

**Comment by chhsiao90** [comment]
Thanks for the report.
Currently, I don't have WebSphere to have a test on it.
Can you provide a complete stack trace and maybe I can figure what's the problem with that? Thanks!

**Comment by robertfmurdock** [comment]
`Caused by: java.lang.reflect.InvocationTargetException
                at sun.reflect.GeneratedMethodAccessor664.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
                at java.lang.reflect.Method.invoke(Method.java:613)
                at org.modelmapper.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:413)
                at org.modelmapper.internal.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
                ... 109 more
Caused by: java.lang.NoClassDefFoundError: org.modelmapper.internal.cglib.proxy.Factory
                at java.lang.ClassLoader.defineClassImpl(Native Method)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:295)
                ... 114 more
Caused by: java.lang.ClassNotFoundException: org.modelmapper.internal.cglib.proxy.Factory
                at java.net.URLClassLoader.findClass(URLClassLoader.java:599)
                at com.ibm.ws.bootstrap.ExtClassLoader.findClass(ExtClassLoader.java:240)
                at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:743)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:720)
                at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:133)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:690)
                at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:62)
                at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:58)
                at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:585)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:690)`

I think this is the relevant part of the stack.

**Comment by chhsiao90** [comment]
Thanks for the stacktrace!
I guess that the problem might relate to class loader and class loading.
When cglib want to load a class with reflection, it used an unexpected class loader so it cannot find the class.

Is that ModelMapper and the source type/destination type of the PropertyMap defined in different class loader?

**Comment by robertfmurdock** [comment]
It looks to me like the org.modelmapper.internal.cglib.proxy.Factory class can't be loaded for some reason, and therefore all sorts of downstream problems occur. AFAIK the model mapper and source/destination types are all defined in the same class loader for the same EAR file.

**Comment by chhsiao90** [comment]
OK.
Maybe you can try
```java
Class.forName("org.modelmapper.internal.cglib.proxy.Factory")
Class.forName("org.modelmapper.internal.cglib.proxy.Enhancer")
Class.forName("org.modelmapper.internal.cglib.core.ReflectUtils")
```
To see that WebSphere loading the classes correctly or not.
I expect all of these three lines code will be fine to load the class.
If not, what's the result for each line of code? And I think... yeah,  you are right about that WebSphere cannot load the class org.modelmapper.internal.cglib.proxy.Factory or package org.modelmapper.internal.cglib.proxy for some reason.
Let's narrow down the problem!

**Comment by robertfmurdock** [comment]
Sorry I haven't gotten back to this - the current setup we have means actually testing this means going through a third party to do the build and that machine has been low availability the last few days. Legacy code... sigh. I'll let you know when I get more information.

**Comment by chhsiao90** [comment]
Sure! Please take your time.
I will also try by myself when I have time.
