### ISSUE TITLE
MappingException on CollectionConverter with 1.0.0 version

### ISSUE THREAD

**Issue by maxbax** [modelmapper/modelmapper#241]
Hi, I'm trying to use the last version (1.0.0) and when my app starts I receive this exception:

1) Converter org.modelmapper.internal.converter.CollectionConverter@57872c9 failed to convert java.util.List to io.realm.RealmList.

The previous version doesn't present that error.
Other stacktrace error details:

at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
ed by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List org.modelmapper.spi.Mapping.getDestinationProperties()' on a null object reference
at org.modelmapper.internal.MappingEngineImpl.destinationProperty(MappingEngineImpl.java:343)
at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:114)
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
at org.modelmapper.internal.converter.IterableConverter.convert(IterableConverter.java:49)
at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:366)
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:96)
at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:252)
at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:186)
at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:135)
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
... 13 more

Thanks
Max

**Comment by chhsiao90** [comment]
@maxbax - Thanks for the report. Can you provide a minimum reproducer or sample code? I think I need this to figure out what's happen with your case, thanks!

**Comment by johnluetke** [comment]
I am also having a smiliar issue with converting Collections after upgrading to 1.0.0.

```
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Converter org.modelmapper.internal.converter.ArrayConverter@4db355ea failed to convert java.util.List to [Ljava.lang.Object;.
```

To clarify, the conversion fails when trying to map a ```List<?>``` to ```Object[]```. I reported a similar issue in #220 

A custom PropertyMap is not producing the error.

```MappingengineImpl:343``` is throwing a *NullPointerException* because the ```intermediateDest``` value is null.

It appears to be instantiated as null when the ```ArrayConverter``` (or the ```CollectionConverter``` in @maxbax's case) attempts to create the destination. In my case, it is returning an array of the proper length, but with ```null``` values, instead of newly instantiated objects

**Comment by chhsiao90** [comment]
@johnluetke - Thanks for the comment.
I still cannot figure out what caused the exception to be throw and I think this issue is different to #220.
If you could provide any reproducible code or something about source type and destination type, to let me know what is the case about, I will appreciate it!

And it seems that you had figured out a solution for this bug, it will be great to have a PR with bugfix and an unit test if you want, thanks!

**Comment by johnluetke** [comment]
I can do that. Thanks for the invitation to do so. I'll open a pull request
once I have it ready.
