### ISSUE TITLE
`NullPointerException` when using `skip` on setters with long primitive type on 1.0.0

### ISSUE THREAD

**Issue by carofe82** [modelmapper/modelmapper#242]
```java
import org.modelmapper.ModelMapper;
import org.modelmapper.config.Configuration.AccessLevel;
import org.modelmapper.convention.MatchingStrategies;

public class Main {
	public static void main(String[] args) {
		thisOneWorks();
		thisOneDoesNotWork();
	}
	
	private static void thisOneWorks() {
		ModelMapper modelMapper = new ModelMapper();
		modelMapper.getConfiguration()
			.setFieldMatchingEnabled(true)
			.setMatchingStrategy(MatchingStrategies.STRICT)
			.setFieldAccessLevel(AccessLevel.PRIVATE);

		modelMapper.createTypeMap(SourceTest.class, DestinationWithObjectTest.class)
			.addMappings(mapper -> mapper.skip(DestinationWithObjectTest::setLongObject));
		modelMapper.validate();
	}
	
	private static void thisOneDoesNotWork() {
		ModelMapper modelMapper = new ModelMapper();
		modelMapper.getConfiguration()
			.setFieldMatchingEnabled(true)
			.setMatchingStrategy(MatchingStrategies.STRICT)
			.setFieldAccessLevel(AccessLevel.PRIVATE);

		modelMapper.createTypeMap(SourceTest.class, DestinationWithPrimitiveTest.class)
			.addMappings(mapper -> mapper.skip(DestinationWithPrimitiveTest::setLongPrimitive));
		modelMapper.validate();
	}
}

class SourceTest {
	
}

class DestinationWithObjectTest {
	private Long longObject;

	public void setLongObject(Long longObject) {
		this.longObject = longObject;
	}
}

class DestinationWithPrimitiveTest {
	private long longPrimitive;
	public void setLongPrimitive(long longPrimitive) {
		this.longPrimitive = longPrimitive;
	}
}
```

Exception:
```
Exception in thread "main" java.lang.NullPointerException
	at org.modelmapper.internal.ReferenceMapExpressionImpl.skip(ReferenceMapExpressionImpl.java:64)
	at org.modelmapper.internal.ConfigurableMapExpressionImpl.skip(ConfigurableMapExpressionImpl.java:73)
	at Main.lambda$1(Main.java:32)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:236)
	at Main.thisOneDoesNotWork(Main.java:32)
	at Main.main(Main.java:9)
```

It is trying to call the `setLongPrimitive` setter with the value `null`. It is assuming that the default value for that property is `null`.

**Comment by chhsiao90** [comment]
@carofe82 - Thanks for the report, I think that's a bug, I will fix it!

**Comment by chhsiao90** [comment]
I think #244 will resolve this bug.

**Comment by chhsiao90** [comment]
@carofe82 - #244 had been release with v1.1.0, please have a try! thanks.

**Comment by carofe82** [comment]
Thank you! I'll give it a try this week.

**Comment by lovabill** [comment]
Same for primitive int. Thank you.
