### ISSUE TITLE
ModelMapper should support Builder Pattern

### ISSUE THREAD

**Issue by Vadus** [modelmapper/modelmapper#265]
By default the ModelMapper passes values from a source bean to a target bean by getter and setter methods. However, if immutable DTOs, instead of POJOs, should be created ModelMapper should support the Builder pattern.

For instance: We want to map from a mutable Source (e.g. Entity) to a immutable Target DTO

`
class Source {
    
    private Long a;
    private String b;
    
    public Long getA() {
        return a;
    }
    public void setA(Long a) {
        this.a = a;
    }
    public String getB() {
        return b;
    }
    public void setB(String b) {
        this.b = b;
    }
}

class Target {
    
    private Long internalId;
    private String externalId;
    
    private Target(Builder builder) {
        this.internalId = builder.internalId;
        this.externalId = builder.externalId;
    }
    public Long getInternalId() {
        return internalId;
    }
    public String getExternalId() {
        return externalId;
    }
   
    public static Builder builder() {
        return new Builder();
    }
    
    public static final class Builder {
        private Long internalId;
        private String externalId;

        private Builder() {}

        public Builder withInternalId(Long internalId) {
            this.internalId = internalId;
            return this;
        }

        public Builder withExternalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        public Target build() {
            return new Target(this);
        }
    }
}
`
It should be possible to configure ModelMapper, so that the Target.Builder class is being used. Specific Mappings (Source.a -> Target.InternalId , Source.b -> Target.ExternalId) must be applied to the Builder pattern.

**Comment by idntfy** [comment]
You can just map to builder instance, in our project we do it for our protobuf-generated sources and it works fine.

Like

```
modelMapper.map(source, Target.Builder.class).build()
// or
modelMapper.map(source, Target.builder()).build()
```

Pretty generic, and obviates the need to have a super-smart pattern-recognition logic in ModelMapper.

**Comment by anticlockwise** [comment]
@idntfy it doesn't work for nested properties though...

**Comment by anticlockwise** [comment]
I have tried supplying a provider that provides an instance of Builder for the model class, but there were errors when modelmapper tries to validate the constructed Builder against the destination type, which is the Model class... If I can somehow bypass the validation logic...

**Comment by fssrepository** [comment]
builder pattern is cumbersome, i used most of the time in test code, and i realized that it's very painful to change. In test i would use json load and jackson. In real code most of the time we are not getting the information from the client, transforming and saving. (No real use of builder pattern)

**Comment by FlameDuck** [comment]
@idntfy I can't get this to work with lombok unfortunately.

**Comment by chhsiao90** [comment]
Hi @FlameDuck - Can you provide more detail? Thanks.

**Comment by FlameDuck** [comment]
@chhsiao90 I have tried to make a small example to illustrate what I am doing:

`package dk.acto.modelmappertest;

import lombok.Builder;
import lombok.Data;
import org.modelmapper.ModelMapper;

public class Main {

    public static void main(String[] args) {
        MyEntity subject = new MyEntity();
        subject.setId(0L);
        subject.setName("subject");
        subject.setValue("test");
        ModelMapper mapper = new ModelMapper();
        MyDto result = mapper.map(subject, MyDto.MyDtoBuilder.class).build();
        System.out.println(result);


    }

    @Data
    private static class MyEntity {
        private Long id;
        private String name;
        private String value;
    }

    @Data
    @Builder
    private static class MyDto {
        private final Long id;
        private final String name;
        private final String value;
    }
}`

This prints: `Main.MyDto(id=null, name=null, value=null)` where I would expect `Main.MyDto(id=0, name="subject", value="test")`

I apologise for my previous rather incomplete answer.

**Comment by chhsiao90** [comment]
hi @FlameDuck,

Please try below configuration and I will think about if I can improve the API.

```java
    Configuration builderConfiguration = modelMapper.getConfiguration().copy();
    builderConfiguration.setDestinationNamingConvention((name, type) -> true);
    builderConfiguration.setDestinationNameTransformer((name, type) -> name);
    modelMapper.createTypeMap(MyEntity.class, MyDto.MyDtoBuilder.class, builderConfiguration);
```

**Comment by chhsiao90** [comment]
I update API for supporting builder pattern.

```java
Configuration builderConfiguration = modelMapper.getConfiguration().copy()
    .setDestinationNameTransformer(NameTransformers.BUILDER)
    .setDestinationNamingConvention(NamingConventions.BUILDER);
modelMapper.createTypeMap(Source.class, Destination.Builder.class, builderConfiguration);
```

**Comment by gopalc** [comment]
@chhsiao90 
I am using
<dependency>
			<groupId>org.modelmapper.extensions</groupId>
			<artifactId>modelmapper-protobuf</artifactId>
			<version>2.2.0</version>
		</dependency>


 and trying to convert POJO to protobuf object
 InputInstruction inputInstruction = InputInstruction.builder().type("input_instruction").schedules(Arrays.asList(new Schedule[]{schedule1, schedule2})).build();

DestinationtionProto.Instruction.Builder sb = modelMapper.map(inputInstruction, DestinationtionProto.InstructionBuilder.class);

but schedules objects not mapping into protobuf object.
can you please help

**Comment by gopalc** [comment]
Below test case is failin

    @Test
    public void testConverter1() {
        Element2 element21 = Element2.builder().name("Name1").grade("grade1").build();
        Element2 element22 = Element2.builder().name("Name2").grade("grade2").build();
        ArrayList<Element2> el = new ArrayList<>();
        el.add(element21);
        el.add(element22);
        Element1 element1 = Element1.builder().element2s(el).build();
        ArrayList el1 = new ArrayList<>();
        el1.add(element1);
        SourceInput sourceInput = SourceInput.builder().element1s(el1).type("t1").status("s1").build();
        ModelMapper modelMapper = new ModelMapper();

        DestinationInstructionProto.Destination.Builder db = modelMapper.map(sourceInput, DestinationInstructionProto.Destination.Builder.class);
        DestinationInstructionProto.Destination destinationProto = db.build();
        Assert.assertTrue(destinationProto.getE1List().size()>0);
    }

-----------------------------  .proto file---------------------------------------
syntax = "proto3";

package demo;

option java_package = "com.sample.protobuf.message";
option java_outer_classname = "DestinationInstructionProto";

message Destination {
    string type = 1;
    repeated Element1 e1 = 2;
    string status = 3;
}

message Element1 {
    repeated Element2 e2 = 2;
  }

message Element2 {
    string name = 1;
    string grade = 2;
  }
------------------------------------------------

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SourceInput {
   public String type;
   public List<Element1> element1s;
   private String status;

}
--------------------------
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Element1 {
    public List<Element2> element2s;

}
-----------------------------
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Element2 {
    String name;
    String grade;

}

**Comment by gopalc** [comment]
After adding modelMapper.registerModule(new ProtobufModule()); getting below error.

Caused by: java.lang.NoSuchMethodException: com.sample.protobuf.message.DestinationInstructionProto$Destination$Builder.getE1()

**Comment by gopalc** [comment]
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping com.instruction.model.SourceInput to com.sample.protobuf.message.DestinationInstructionProto$Destination$Builder

1 error

	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:447)
	at com.instruction.service.ScheduleInstructionServiceImplTest.testConverter1(ScheduleInstructionServiceImplTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Cannot get the member

1 error
	at org.modelmapper.internal.Errors.toMappingException(Errors.java:258)
	at org.modelmapper.protobuf.ProtobufValueWriter.getMember(ProtobufValueWriter.java:70)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveMutatorsFromValueWriter(PropertyInfoSetResolver.java:100)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveMutators(PropertyInfoSetResolver.java:92)
	at org.modelmapper.internal.TypeInfoImpl.getMutators(TypeInfoImpl.java:76)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:98)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:88)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:73)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:129)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:103)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:112)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	... 26 more
Caused by: java.lang.NoSuchMethodException: com.sample.protobuf.message.DestinationInstructionProto$Destination$Builder.getE1()
	at java.lang.Class.getMethod(Class.java:1786)
	at org.modelmapper.protobuf.ProtobufHelper.getter(ProtobufHelper.java:61)
	at org.modelmapper.protobuf.ProtobufValueWriter.getMember(ProtobufValueWriter.java:53)
	... 36 more
