### ISSUE TITLE
Combining skip() and setPropertyCondition() doesn't skip in 1.1.0 but it does in 0.7.5

### ISSUE THREAD

**Issue by ninaolo** [modelmapper/modelmapper#267]
When combining `skip()` with `setPropertyCondition()` the `skip()` no longer seems to work.

An example:

```
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;

public class MyTest {

    private static class A {}

    private static class B {
        void setSomething(String something) {
            throw new NullPointerException("BAD");
        }
    }

    @Test
    public void test() {
        ModelMapper m = new ModelMapper();
        m.getConfiguration().setPropertyCondition(mappingContext -> mappingContext.getSource() != null);
        m.addMappings(new PropertyMap<A, B>() {
            @Override protected void configure() {
                skip().setSomething(null);
            }
        });
        m.map(new A(), new B());
    }
}
```

This test fails and throws a NPE ("BAD"). When removing the `setPropertyCondition(...)` line, the test is green. It seems like this problem was introduced when we switched from `0.7.5` to `1.1.0`. I tried switching back to `0.7.5`, and then the above `test()` is green.

Below is the stacktrace:

```
1) Failed to set value 'null' on my.package.MyTest$B.setSomething()

1 error
	at org.modelmapper.internal.Errors.toMappingException(Errors.java:258)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:127)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:256)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:186)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:135)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:125)
	... 40 more
Caused by: java.lang.NullPointerException: BAD
	at my.package.MyTest$B.setSomething(MyTest.java:13)
	... 45 more
```

**Comment by jelgh** [comment]
+1

**Comment by chhsiao90** [comment]
Fixed by #272 and will be released in next version

**Comment by jelgh** [comment]
Thanks, any estimate on when that will be @chhsiao90 ?

**Comment by chhsiao90** [comment]
I will have a release this weekend!
