### ISSUE TITLE
modelmapper can not map string -> list if add propertyMap

### ISSUE THREAD

**Issue by wyzssw** [modelmapper/modelmapper#269]
I can produce it by following code

```java
import java.util.Arrays;
import java.util.List;

import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;


public class Test {
  public static void main(String[] args) {
    ModelMapper modelMapper = new ModelMapper();
    PropertyMap<Source,Dest> propertyMap = new PropertyMap<Source, Dest>() {
      @Override
      protected void configure() {
        map().setList(Arrays.asList(source.getSrc().split(",")));
      }
    };
    
    modelMapper.addMappings(propertyMap);
    Source source = new Source();
    source.setSrc("1,2,3");
    Dest dest =  modelMapper.map(source, Dest.class);
    System.out.println(dest.getList());
  }
  
  public static class Source{
    private String src;

    public String getSrc() {
      return src;
    }

    public void setSrc(String src) {
      this.src = src;
    }
    
  }
  
  public static class Dest{
    private List<String> list;

    public List<String> getList() {
      return list;
    }

    public void setList(List<String> list) {
      this.list = list;
    }
  }
 

}

```

Exceeption is 
```
Exception in thread "main" org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Cannot map final type java.lang.String.

2) Invalid destination method java.lang.String.split(). Ensure that method has one parameter and returns void.

3) A mapping is missing a required destination member.

3 errors
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:229)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:103)
	at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
```

**Comment by chhsiao90** [comment]
```PropertyMap.configure``` only accept getter/setter, using(converter), when(condition), with(provider). Other things written in the method will probably break the ModelMapper.

Please try ```using(strToStringConverter).map(source.getSrc()).setList(null)``` in the ```configure()``` method, thanks.

**Comment by wyzssw** [comment]
I get it,Thanks

**Comment by JuricaJaman** [comment]
can u provide full example??

**Comment by JuricaJaman** [comment]
got it working not sure why it works like that , spend few hours to make it work with split string

**Comment by wyzssw** [comment]
@JuricaJaman 
```java
 Converter<String, List<String>> strToList =
        ctx -> ctx.getSource() == null ? null : Arrays.asList(ctx.getSource().split(","));
    
    PropertyMap<Source,Dest> propertyMap = new PropertyMap<Source, Dest>() {
      @Override
      protected void configure() {
        using(strToList).map(source.getSrc()).setList(null);
      }
    };

```

**Comment by JuricaJaman** [comment]
@wyzssw thanks, got it the same :)

**Comment by prvn-vrma** [comment]
After so many tries finally worked for me. Although things were available at other places also but it was kind of looking very old to me or some syntax related issue as putting `null` was confusing. 
Very weird syntax to do but yes finally worked.
Thanks
