### ISSUE TITLE
NPE after adding custom mapping with PropertyMap

### ISSUE THREAD

**Issue by tommus** [modelmapper/modelmapper#274]
Does this library support Android?

I am creating an application and decided to use [modelmapper](https://github.com/modelmapper/modelmapper) (great work BTW!).

Until now, I had no problems with using mapper (simple POJOs, conventional mapping) but since yesterday I am trying to add custom mapping definition for my model from Firebase. Once I did this - I cannot resolve the issue with NPE exception that is being thrown by `.addMappings()` method.

Exact exception on which I stuck:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.windly.mappertest/co.windly.mappertest.MainActivity}: org.modelmapper.ConfigurationException: ModelMapper configuration errors:
    
    1) Error reading class co.windly.mappertest.converters.CinemaPropertyMap
    
    2) Failed to configure mappings
    
    2 errors
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: org.modelmapper.ConfigurationException: ModelMapper configuration errors:
    
    1) Error reading class co.windly.mappertest.converters.CinemaPropertyMap
    
    2) Failed to configure mappings
    
    2 errors
        at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
        at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:213)
        at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
        at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:103)
        at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
        at co.windly.mappertest.MainActivity.onCreate(MainActivity.kt:60)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
          ... 9 more
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at org.modelmapper.internal.ExplicitMappingBuilder.validateVisitedMappings(ExplicitMappingBuilder.java:243)
        at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:234)
        at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:196)
          ... 16 more

I've added a [repository](https://github.com/tommus/modelmapper-test) that reproduces this exact issue.

Any help / response would be much appreciated. Thanks.

**Comment by chhsiao90** [comment]
Hi, thanks for the report!

ModelMapper currently doesn't support Android well (explicit mapping). Please reference #87 for more detail. And I guessed that it throw NullPointerException instead of a more meaningful exception is caused by the bugfix of #260 (I think I can take a look for this part).

Support Android/Kotlin is a huge work I'm not sure that I had time to implement that..

**Comment by chhsiao90** [comment]
Another ref: https://groups.google.com/forum/#!topic/modelmapper/m949j-tUpVw

**Comment by tommus** [comment]
In issue #87 it has been suggested the problem was in Cglib. It's no longer valid since Cglib has been replaced with ByteBuddy in version 2.0.0. Any further investigations on this?
