### ISSUE TITLE
Map<String, List<SomeObject>>: not mapped

### ISSUE THREAD

**Issue by SomeDude1234** [modelmapper/modelmapper#278]
Hello,

I need to map an Object that contains a Map<String, List<OtherObject>> to my own classes.
But the List with OtherObject seems not to be mapped to my classes but to the same classes resulting in a classcastexception. Is this a bug or am I missing some config setting?

Sample code:
`public class MapWithListBug {

    private ModelMapper modelMapper;

    @Before
    public void init() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STANDARD);
        //http://modelmapper.org/getting-started/#validating-matches
        modelMapper.validate();
    }

    @Test
    public void testMapToDto() {
        A source = buildA();
        ADto aDto = modelMapper.map(source, ADto.class);

        Assert.assertNotNull(aDto);
        Assert.assertEquals(aDto.getAuthor(), "Author");
        Assert.assertNotNull(aDto.getMyMap());
        Assert.assertEquals(2, aDto.getMyMap().size());

        List<BDto> firstList = aDto.getMyMap().get("key 1");
        Assert.assertNotNull(firstList);
        Assert.assertEquals(1, firstList.size());

        BDto bDto = firstList.get(0);
        Assert.assertNotNull(bDto);
        Assert.assertEquals(new Double(2.15), bDto.getDuration());
        Assert.assertEquals(true, bDto.getEnglish());
        Assert.assertEquals("a title", bDto.getTitle());
        //TODO
    }

    private A buildA() {
        A a = new A();

        a.setAuthor("Author");
        a.setMyMap(buildMap());

        return a;
    }

    private Map<String,List<B>> buildMap() {
        Map<String,List<B>> map = new HashMap<>();

        map.put("key 1", buildList());
        map.put("key 2", buildList());

        return map;
    }

    private List<B> buildList() {
        List<B> list = new ArrayList<>();

        list.add(buildB());

        return list;
    }

    private B buildB() {
        B b= new B();

        b.setDuration(new Double(2.15));
        b.setEnglish(true);
        b.setTitle("a title");

        return b;
    }

}
`

`public class A {

    private String author;
    private Map<String, List<B>> myMap;

    public A() {
        this.myMap = new HashMap<>();
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Map<String, List<B>> getMyMap() {
        return myMap;
    }

    public void setMyMap(Map<String, List<B>> myMap) {
        this.myMap = myMap;
    }
}
`

`public class B {

    private String title;
    private Boolean english;
    private Double duration;

    public B() {

    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getEnglish() {
        return english;
    }

    public void setEnglish(Boolean english) {
        this.english = english;
    }

    public Double getDuration() {
        return duration;
    }

    public void setDuration(Double duration) {
        this.duration = duration;
    }
}`

`public class ADto {

    private String author;
    private Map<String, List<BDto>> myMap;

    public ADto() {
        this.myMap = new HashMap<>();
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Map<String, List<BDto>> getMyMap() {
        return myMap;
    }

    public void setMyMap(Map<String, List<BDto>> myMap) {
        this.myMap = myMap;
    }
}
`

`public class BDto {

    private String title;
    private Boolean english;
    private Double duration;

    public BDto() {

    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getEnglish() {
        return english;
    }

    public void setEnglish(Boolean english) {
        this.english = english;
    }

    public Double getDuration() {
        return duration;
    }

    public void setDuration(Double duration) {
        this.duration = duration;
    }
}`

**Comment by chhsiao90** [comment]
It's a bug, but I'm not sure that I can fix this issue. Handling generic type is always hard, and I have no idea how to fix this bug at this moment. I will try to figure out a fix.

**Comment by chhsiao90** [comment]
Hi, I think we can't solve the problem because the generic types are only exist in compile time, we can't know the generic in runtime.

So I think it needs a converter for this map<->map mapping.
```java
Converter<Map<String, List<B>>, Map<String, List<BDto>>> converter = new Converter<>() {
  @Override
  public Map<String, List<BDto>> convert(MappingContext<Map<String, List<B>>, Map<String, List<BDto>>> context) {
    Map<String, List<BDto>> destination = new HashMap<>();
    for (Entry<String, List<B>> entry : context.getSource().entrySet()) {
      List<BDto> bDtos = context.getMappingEngine().map(context.create(entry.getValue(), new TypeToken<List<BDto>>() {}.getType()));
      destination.put(entry.getKey(), bDtos));
    }
    return destination;
  }
};
modelMapper.addMappings(new PropertyMap<>() {
  @Override
  public void configure() {
    using(converter ).map(source.getMyMap(), destination.getMyMap());
  }
});
```

Sorry for this inconvenience :(

**Comment by vld0** [comment]
Hi, in my case the solution above does not work.
I get this exception:

> Caused by: java.lang.IllegalArgumentException: Expected 1 argument for generic type java.util.Map<java.lang.String, java.util.List<BDto>> but found 2

I tried to improve the converter but I get the initial class cast exception.
`Converter<Map<String, List<B>>,
                Map<String, List<BDto>>> converter =
                mappingContext -> {
                    Type mapType = new TypeToken< Map<String, List<BDto>> >() {}.getType();
                    Map<String, List<BDto>> result = mappingContext.getMappingEngine()
                            .map(mappingContext.create(mappingContext.getSource(),
                                    mapType)
                            );
                    return result;
                };`

**Comment by chhsiao90** [comment]
The following code is necessary for your converter.

```
    for (Entry<String, List<B>> entry : context.getSource().entrySet()) {
      List<BDto> bDtos = context.getMappingEngine().map(context.create(entry.getValue(), new TypeToken<List<BDto>>() {}.getType()));
      destination.put(entry.getKey(), bDtos));
    }
```

**Comment by vld0** [comment]
Thanks for your quick answer. Unfortunately I can not make it work.
Steps to reproduce:
- Copy the example from the initial post https://github.com/modelmapper/modelmapper/issues/278#issue-272098913
- Add your converter
Here is the exception I get:

> org.modelmapper.MappingException: ModelMapper mapping errors:

1) Converter org.modelmapper.internal.converter.MergingCollectionConverter@61fe30 failed to convert java.util.ArrayList to java.util.List.
Caused by: java.lang.IllegalArgumentException: Expected 1 argument for generic type java.util.Map<java.lang.String, java.util.List<BDto>> but found 2
	at org.modelmapper.internal.typetools.TypeResolver.resolveRawArgument(TypeResolver.java:218)
	at org.modelmapper.internal.util.MappingContextHelper.resolveDestinationGenericType(MappingContextHelper.java:54)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:47)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:31)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:306)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:109)
	at MapWithListBug$1.convert(MapWithListBug.java:46)
	at MapWithListBug$1.convert(MapWithListBug.java:31)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:306)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:243)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:187)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:105)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:406)
	at MapWithListBug.testMapToDto(MapWithListBug.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	...<lines removed>...	

2) Converter org.modelmapper.internal.converter.MergingCollectionConverter@61fe30 failed to convert java.util.ArrayList to java.util.List.
Caused by: java.lang.IllegalArgumentException: Expected 1 argument for generic type java.util.Map<java.lang.String, java.util.List<BDto>> but found 2
	at org.modelmapper.internal.typetools.TypeResolver.resolveRawArgument(TypeResolver.java:218)
	at org.modelmapper.internal.util.MappingContextHelper.resolveDestinationGenericType(MappingContextHelper.java:54)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:47)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:31)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:306)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:109)
	at MapWithListBug$1.convert(MapWithListBug.java:46)
	at MapWithListBug$1.convert(MapWithListBug.java:31)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:306)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:243)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:187)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:105)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:406)
	at MapWithListBug.testMapToDto(MapWithListBug.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	...<lines removed>...

2 errors

	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:406)
	at MapWithListBug.testMapToDto(MapWithListBug.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	...<lines removed>...
