### ISSUE TITLE
NPE when creating proxy for a class type that cannot be loaded 

### ISSUE THREAD

**Issue by mdzhigarov** [modelmapper/modelmapper#293]
I am getting the following NPE:

 ```
1) Failed to configure mappings

 1 error
       at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
       at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:213)
       at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:89)
       at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:103)
       at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:94)
       ...
 Caused by: java.lang.NullPointerException
       at org.modelmapper.internal.ExplicitMappingBuilder$ExplicitMappingInterceptor.access$000(ExplicitMappingBuilder.java:284)
       at org.modelmapper.internal.ExplicitMappingBuilder.createAccessorProxies(ExplicitMappingBuilder.java:267)
       at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:257)
       at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:236)
       at org.modelmapper.PropertyMap.configure(PropertyMap.java:382)
       at sun.reflect.GeneratedMethodAccessor812.invoke(Unknown Source) [:1.8.0_152]
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_152]
       at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_152]
       at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:196)
       ... 48 more
```

Using the debugger I identified that ProxyFactory#proxyClassFor() line 68 throws NoClassDefFoundError,
because cglib cannot load the type - javax.xml.datatype.XMLGregorianCalendar in this case. 
This is OK, since I run in an OSGi container and the class is indeed not loadable by the current bundle classloader.

However, I have defined an explicit mapping, i.e: modelMapper.getConfiguration().setImplicitMappingEnabled(false);

And the property who's type is javax.xml.datatype.XMLGregorianCalendar is not even part of the explicit mapping that I defined.
Therefore, I expect that ModelMapper should not even attempt to map it.
So a NPE is not ideal here. 
I would say that skipping the type is better since it may not even be part of the explicit mapping

**Comment by mdzhigarov** [comment]
Closing this issue. Seems that ModelMapper is correctly setting the classloader in cglib's Enchancer but since the classloader is not able to load the type, proxying simply fails.
Unfortunately, there is nothing that ModelMapper can do in this case since the failure happens in cglib.

The client code must make sure that if it runs withing an OSGi container, the classloader of the weaved class must be able to load all properties within its own reflection hierarchy.

Not ideal though :/

**Comment by mdzhigarov** [comment]
Reopening the issue because of the NPE.

Instead of NPE the user should be able to see the original error that cglib threw - the NoClassDefFoundError in that case.

I noticed that the code:
```
private <T> T createProxy(Class<T> type) {
    ExplicitMappingInterceptor interceptor = new ExplicitMappingInterceptor();

    try {
      T proxy = ProxyFactory.proxyFor(type, interceptor, proxyErrors);
      proxyInterceptors.put(proxy, interceptor);
      return proxy;
    } catch (ErrorsException e) {
      return null;
    }
  }
```
simply swallows the ErrorsException that the proxy factory throw and returns null.
Seems this was changed recently. 
Any idea why? I think we should throw the exception so that the user can see what actually got wrong.
Returning null simply results in a NPE later when the ExplicitMappingBuilder tries to access the source/destination proxies

**Comment by mdzhigarov** [comment]
Related to https://github.com/modelmapper/modelmapper/issues/287

The NPE still occurs, just at another location

**Comment by chhsiao90** [comment]
Okay, I will take a look for this issue.

**Comment by chhsiao90** [comment]
Hi @mdzhigarov, Can you provide reproducible code and stacktrace to me? Thank you.
