### ISSUE TITLE
Nullpointer exception on Websphere stack

### ISSUE THREAD

**Issue by phazebroek** [modelmapper/modelmapper#310]
With version 1.1.2 I get a NullPointerException on the following code:

`.addMappings(mapping -> mapping.skip(Foo::setSomeProperty))`

The field I want it to skip is a primitive boolean annotated with @Transient.

The error I get is:
```
Caused by: java.lang.NullPointerException: null
	at com.foo.bar.configuration.ModelMapperConfiguration$$Lambda$83.00000000F4A8F110.accept(Unknown Source)
	at org.modelmapper.internal.ReferenceMapExpressionImpl.skip(ReferenceMapExpressionImpl.java:83)
	at org.modelmapper.internal.ConfigurableMapExpressionImpl.skip(ConfigurableMapExpressionImpl.java:73)
	at com.foo.bar.configuration.ModelMapperConfiguration.lambda$mapFoo$29(ModelMapperConfiguration.java:119)
```

Where ModelMapperConfiguration.java:119 refers to the line I mentioned above.
Commenting out that line resolves the issue and allows me to boot my app again.

Note: this exact same code works perfectly on tomcat!

I have confirmed classloader is loading the right jar file (1.1.2)

I can reproduce the exact same error locally on my machine (running the spring-boot app on an embedded tomcat) when I downgrade the dependency to 1.0.0 for example. However when I upgrade back to 1.1.2 the issue is resolved for me locally and on tomcat environment, but as I said, not yet on websphere.

Can you please have a look? thanks!

**Comment by phazebroek** [comment]
Issue can be closed again.
Apparently there was a change on our websphere environment (infra team changed the vendor of the JVM to IBM and there was a bug in it... after upgrading to latest the issue magically disappeared)
