### ISSUE TITLE
ModelMapper trying to map MyEntity.id > MyDto.callerId

### ISSUE THREAD

**Issue by leonroy** [modelmapper/modelmapper#312]
ModelMapper seems to be trying to map the property of my Dto `String callerId` onto a property of my Entity `Long id`.

DTO:

```
@Accessors(chain = true)
@ApiModel("Requires at least `phoneNumber`")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EndpointCreateDto {

    @NotNull(message = "Phone number is required.")
    private String phoneNumber;

    private String callerId;

    private String label;

}
```

Entity:

```
@Accessors(chain = true)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Endpoint implements RestEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @NotEmpty(message = "Phone number is required.")
    private String phoneNumber;

    private String callerId;

    private String label;

    @Transient
    @ManyToOne(optional = false)
    private User user;

    private boolean verified;


}
```

if I try to `map(dto, Endpoint.class`) I get the following error:

```
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Converter org.modelmapper.internal.converter.NumberConverter@7ac7a4e4 failed to convert java.lang.String to java.lang.Long.

1 error

	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:374)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:69)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:529)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:372)
	at com.example.server.EndpointDtoUnitTest.testConvertCreateDtoToEntity(EndpointDtoUnitTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping My Caller Id to java.lang.Long

1 error
```

**Comment by chhsiao90** [comment]
Can you try [skipping-properties](http://modelmapper.org/user-manual/property-mapping/#skipping-properties) or [MatchingStrategy.Strict](http://modelmapper.org/user-manual/configuration/#matching-strategies)? Thanks.

**Comment by leonroy** [comment]
better late than never! yes indeed the below config solved it:

```
@Bean
    public ModelMapper modelMapper() {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration()
                .setMatchingStrategy(MatchingStrategies.STRICT);
}
```
