### ISSUE TITLE
Error using miltiple providers, ModelMapper is getting one to another property

### ISSUE THREAD

**Issue by eapereira** [modelmapper/modelmapper#328]
Hello folka, I have two providers and ModelMapper is using the one to the wrong property! In my case I have UserProvider and UfProvider, it is calling UserProvider to a instance of UfUi and I got this error:

1) Failed to set value 'UserModel [dtNasc=null, idUf=null, login=null, name=null, password=null, urlAvatar=null, cidade=null, posts=[], postScores=[], privatePostScores=[], privatePosts=[], privateTopicUsers=[], testDrives=[], testDriveScores=[], userRoles=[], logins=[], topicUserVieweds=[]]' on br.com.xlib.putariaBR.model.CidadeModel.setUf()

1 error
	at org.modelmapper.internal.Errors.toMappingException(Errors.java:258)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:127)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:256)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:186)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:135)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:92)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:60)
	... 43 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@2220c5f7
	at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:125)
	... 48 more
2018-05-10 20:56:53.150 [ERROR] br.com.xlib.putariaBR.service.impl.AbstractServiceImpl       : org.modelmapper.MappingException: ModelMapper mapping errors:

Here is my mapper:

```
public class CidadePropertyMap
		extends AbstractPropertyMap<CidadeEntity, CidadeUi> {

	private static final Logger LOGGER = LogManager
			.getLogger(CidadePropertyMap.class);

	@Override
	protected void configure() {
		LOGGER.info("BEGIN");
		UserProvider userProvider = new UserProvider();

		with(userProvider).map().setUserAltered(source.getUserAltered());
		with(userProvider).map().setUserCreated(source.getUserCreated());

		UfProvider ufProvider = new UfProvider();
		UserListConverter userListConverter = new UserListConverter();

		with(ufProvider).map().setUf(source.getUf());

		using(userListConverter).map().setUsers(source.getUsers());
		LOGGER.info("END");
	}

}

public class UserProvider extends AbstractProvider<UserUi> {

	@Override
	protected UserUi get() {
		return new UserUi();
	}

}

public class UfProvider extends AbstractProvider<UfUi> {

	@Override
	protected UfUi get() {
		return new UfUi();
	}

}

```

**Comment by chhsiao90** [comment]
There are some problems in your PropertyMap

The PropertyMap is only allowed
- with(...).map(...)
- skip(...).map(...)
- using(...).map(...)

So it's not allowed
```java
protected void configure() {
    LOGGER.info("BEGIN");  // Not allowed
    UserProvider userProvider = new UserProvider();  // Not allowed

    with(userProvider).map().setUserAltered(source.getUserAltered());
    with(userProvider).map().setUserCreated(source.getUserCreated());

    UfProvider ufProvider = new UfProvider();  // Not allowed
    UserListConverter userListConverter = new UserListConverter();  // Not allowed

    with(ufProvider).map().setUf(source.getUf());

    using(userListConverter).map().setUsers(source.getUsers());
    LOGGER.info("END");  // Not allowed
}
```

So I suggest to move these stuff outside the configure and try again.
And if the problem is not solved, please also provide your source/destination model source code, thanks.

**Comment by eapereira** [comment]
How could I use a provider if I cant create its variable?

**Comment by eapereira** [comment]
if I use mapper.addConverter() and mapper.addProvider(), my providers and converters are not called and nothing happens.

**Comment by chhsiao90** [comment]
Can you provide source/destination class source code so that I can provide sample code to you, thanks.
