### ISSUE TITLE
ObjA JSONArray To ObjectB JSONArray

### ISSUE THREAD

**Issue by yakirChen** [modelmapper/modelmapper#335]
**A.java**
```java
public class A {

    private String a;
    private String birth;

    public A() {
    }

    public A(String a,
             String birth) {
        this.a = a;
        this.birth = birth;
    }

    public String getBirth() {
        return birth;
    }

    public void setBirth(String birth) {
        this.birth = birth;
    }

    public String getA() {
        return a;
    }

    public void setA(String a) {
        this.a = a;
    }
}
```

**B.java**
```java
public class B {

    private String b;
    private Date   birthday;

    public B() {
    }

    public B(String b,
             Date birthday) {
        this.b = b;
        this.birthday = birthday;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getB() {
        return b;
    }

    public void setB(String b) {
        this.b = b;
    }
}
```

```java
List<A> listObjs = new ArrayList<>();
A       a        = new A("a", "2018-06-18 08:00:00");
A       a1       = new A("a1", "2018-06-18 08:00:00");
listObjs.add(a);
listObjs.add(a1);

String json = JSON.toJSONString(listObjs);

logger.info("{}", json);
```

I got  JSON

```json
[{"a":"a","birth":"2018-06-18 08:00:00"},{"a":"a1","birth":"2018-06-18 08:00:00"}]
```

```java
        JsonNode jsonNode = objectMapper.readTree(json);

        ModelMapper modelMapper = new ModelMapper();
        Configuration cfg = modelMapper.getConfiguration()
                .addValueReader(new JsonNodeValueReader())
                .setSourceNamingConvention(NamingConventions.NONE)
                .setDestinationNamingConvention(NamingConventions.NONE);

//        Map<String, List<B>> bDup = new HashMap<>();
        List<B> bDup = new ArrayList<>();

        Class<?> destType = new TypeToken<List<B>>() {}.getRawType();

        modelMapper.createTypeMap(jsonNode,
//                new TypeToken<Map<String, List<B>>>() {}.getRawType(),
                destType,
                cfg);

        TypeMap<JsonNode, B> typeMap = modelMapper.createTypeMap(jsonNode, B.class, cfg);
        modelMapper.addMappings(new PropertyMap<JsonNode, B>() {
            @Override
            protected void configure() {
                map().setB(this.source("a"));
                using(new Converters.DateConvertor("yyyy-MM-dd HH:mm:ss"))
                        .map(this.source("birth"),
                                this.destination.getBirthday());
            }
        });

        modelMapper.map(jsonNode, bDup);
```

I always got NPE .

```shell
java.lang.NullPointerException
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveAccessors(PropertyInfoSetResolver.java:78)
	at org.modelmapper.internal.TypeInfoImpl.getAccessors(TypeInfoImpl.java:59)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:161)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:99)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:81)
	at org.modelmapper.internal.TypeMapStore.create(TypeMapStore.java:55)
	at org.modelmapper.ModelMapper.createTypeMapInternal(ModelMapper.java:532)
	at org.modelmapper.ModelMapper.createTypeMap(ModelMapper.java:226)
```

I hope somebody can help me to fix it .

Thanks . 😝

**Comment by chhsiao90** [comment]
hi @yakirChen ,

You only need to setup the mappings for JsonNode <-> B
```
        modelMapper.addMappings(new PropertyMap<JsonNode, B>() {
            @Override
            protected void configure() {
                map().setB(this.source("a"));
                using(new Converters.DateConvertor("yyyy-MM-dd HH:mm:ss"))
                        .map(this.source("birth"),
                                this.destination.getBirthday());
            }
        });
```

And I just found that modelmapper jackson integration is not handling ArrayNode well. Just created a pull request #338 for that.

**Comment by yakirChen** [comment]
Thanks 👏
