### ISSUE TITLE
Mapping collection based on getter only (without setter)

### ISSUE THREAD

**Issue by bsadykov** [modelmapper/modelmapper#366]
Hi !

When using JPA it's often desirable not to use setters for nested collections (e.g. OneToMany), but to operate via getters only. 
Also when using lombok with lazy collections, it's not even possible to declare collection setters.

I tried to declare mapping like this:
```
mapper.typeMap(Entity.class, Dto.class).addMapping(Entity::getElements, (Dto dto, List<ElementEntity> elements) -> {
    if (elements != null) {
        dto.getElements().addAll(elements.stream().map(element -> mapper.map(element, ElementDto.class)).collect(toList()));
    }
})
```
But am getting exception (due to missing collection setter):
```
1) Illegal DestinationSetter defined

1 error
	at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
	at org.modelmapper.internal.PropertyReferenceCollector.collect(PropertyReferenceCollector.java:117)
	at org.modelmapper.internal.ReferenceMapExpressionImpl.map(ReferenceMapExpressionImpl.java:75)
	at org.modelmapper.internal.TypeMapImpl.addMapping(TypeMapImpl.java:231)
	at Mapping.main(Mapping.java:18)
```
Would is be possible to enable this kind of mapping ?

Thank you and keep up the great work !

**Comment by bsadykov** [comment]
The problem I see with the current implementation is that when calling:
```
mapper.map(existingDto, existingJpaEntity)
```
in case existingJpaEntity has nested collections (OneToMany), the collections and all elements inside will be fully recreated instead of updating existing collection (and existing elements).
In that case the collection elements become "detached" from the current JPA session and you need to explicitly call EntityManager.merge and be careful with cascades you use on OneToMany or ManyToMany.
For that reason I would prefer to update collections only via getters.

**Comment by chhsiao90** [comment]
hi @bsadykov ,

You can only call getter/setter in the ```addMapping``` function.
If you want to use ```if```, please use ```when```.
If you want to convert the source's propertie to another type, please use ```use```.

Here is what I think the right way based on your scenario.
```java
mapper.typeMap(Dto.class, Entity.class).addMappings(
    mapper -> mapper.when(Objects::nonNull)
        .using(elements -> elements.stream().map(element -> mapper.map(element, ElementEntity.class)).collect(toList()))
        .map(Dto::getElements, Entity::setElements));
```

**Comment by Hauke85** [comment]
@bsadykov Did you find any viable solution?
I am facing basically the same issue, just without the conversion of the elements of the collection.
I just want the content of the collection to be copied (took out the mapping of the elements to simplify things here).

I wrote a testcase to demonstrate this issue.
Any suggestions how to make this work?
```java
public class CollectionMappingTest {
    @Test
    public void testDesiredCollectionCopyMapping() {
        ModelMapper mapper = new ModelMapper();
        mapper.createTypeMap(CollectionHolderA.class, CollectionHolderB.class)
                .addMappings(mappr -> mappr.map(
                        CollectionHolderA::getStrings,
                        (CollectionHolderB dest, List<String> srcValue) -> {
                            // do not call setter directly, but leave (jpa-)collection
                            // intact, just modify/copy content.
                            if (dest == null || dest.getStrings() == null) return;
                            dest.getStrings().clear();
                            if (srcValue != null) {
                                dest.getStrings().addAll(srcValue);
                            }
                        })
                );
                // disable default mapping -> does not affect the outcome
                // .addMappings(mappr -> mappr.skip(CollectionHolderB::setStrings)); 


        CollectionHolderA original = new CollectionHolderA();
        original.getStrings().addAll(Lists.newArrayList("Foo", "Bar"));

        CollectionHolderB destination = mapper.map(original, CollectionHolderB.class);

        // Must not be equal as we want to keep destination's (jpa-)collection-instance intact
        Assert.assertNotEquals(original.getStrings(), destination.getStrings());

        //Yet, the content has to be the same
        Assert.assertEquals(2, destination.getStrings().size());
        for (String string : original.getStrings()) {
            Assert.assertTrue(destination.getStrings().contains(string));
        }
    }

  /**Testclass just holding a collection*/
    public static class CollectionHolderA {
        private List<String> strings = new ArrayList<>();
        public List<String> getStrings() { return strings;}
        public void setStrings(List<String> strings) {this.strings = strings;}
    }
    /**Testclass just holding a collection*/
    public static class CollectionHolderB {
        private List<String> strings = new ArrayList<>();
        public List<String> getStrings() { return strings;}
        public void setStrings(List<String> strings) {this.strings = strings;}
    }

}
```
In reality the CollectionHolderA & CollectionHolderB would be Jpa-@Entities
