### ISSUE TITLE
Failed mapping of an example of inheritance hierarchy in two different object model 

### ISSUE THREAD

**Issue by wwang2016** [modelmapper/modelmapper#398]
Hi,

I have studied the inheritance example and was able to run it successfully.

However, I have a different case which does not seem to work.

I reused all the BaseDest.java, BaseDestA.java, BaseDestB.java, BaseSrc.java, BaseSrcA.java, BaseSrc.B.java except for changing BaseDest.java and BaseSrc.java to be abstract class. I ran the inheritance example, and it still worked fine.

Now, for my case, I create 
ObjectContainer.java with a 
private BaseSrc instance
ObjectContainer2.java with a 
private BaseDesc instance

For the test class,
I did the following:
ObjectContainer oc = new ObjectContainer();
BaseSrc srcA = new BaseSrcA();
// Note, I had to add a setter method and really need to call it before modelmapper was invoked.
srcA.setaString("testA");  
oc.setInstance(srcA);

with the same type mapping code,
Now, 
ObjectContainer2 oc2 = modelMapper.map( oc, ObjectContainer2.class);

It throwed out exception:
1) Failed to instantiate instance of destination com.test.BaseDest. Ensure that com.test.BaseDest has a non-private no-argument constructor.

Also note that the type mapping was not actually invoked (I added debug code)

If I redefine the BaseDest so that it is not abstract class, the exception is gone, but the instance is not mapped to the sub type (BaseDestA).

I created this simpler test case to show that modelmapper does not work well in this type of scenario. I actually identified this issue in a more complex scenario, and just want to use a simpler model to clarify the problem.

I am hoping there is a different way to configure modelmapper in order to allow subtype mapping properly.

Thanks,

Wayne

**Comment by wwang2016** [comment]
Note: the only difference between my case and the example from source code is the container in my case has one instance defined super type while the container in the example has a List of instance defined as super type.

I actually changed my Container to have a list of instances defined as super type, and the type mapping code was invoked too.

This seems to be a bug that happened when there is only one instance defined as super type.

**Comment by wwang2016** [comment]
I pulled the master branch (2.2.1) and tested with both of the following configurations. However, the issue remains. As I indicated before, the issue will be resolved if the ObjectContainer.java has a List<BaseSrc> instead of one instance of BaseSrc. If the ObjectContainer had only one instance of BaseSrc, then the typemapping would not be invoked, and modelmapper will try to create an instance of super type BaseDest, insteader of BaseDestA.

(1) Your recommended method 
modelMapper.typeMap(BaseSrcA.class, BaseDestA.class).include(BaseDest.class)

or

(2) method in the inheritance example 
TypeMap<BaseSrc, BaseDest> typeMap = modelMapper.createTypeMap( BaseSrc.class, BaseDest.class )
                                                                 .include( BaseSrcA.class, BaseDestA.class )
                                                                 .include( BaseSrcB.class, BaseDestB.class );

The error:
Exception in thread "main" org.modelmapper.MappingException: ModelMapper mapping errors:
1) Failed to instantiate instance of destination com.test.BaseDest. Ensure that com.test.BaseDest has a non-private no-argument constructor.

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:84)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:576)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:407)

**Comment by wwang2016** [comment]
I would like to share one piece of information I identified:
When I add some debug message to the method of MappingEngineImpl.java (public <S, D> D map(MappingContext<S, D> context) {...})
I can see the following message when I test the inheritance example code:
converter: org.modelmapper.internal.converter.CollectionConverter
Basically this converter was invoked. Then the typemapping configuration was invoked.

When I test my test case where it is not a array of super type, this message was not found, and the typemapping configuration was NOT invoked, and it tried to find a non argument non private constructor of super type

**Comment by chhsiao90** [comment]
Thanks for this report. I can reproduce this bug and I will fix it.

**Comment by n1b0r** [comment]
any news on this issue ?

**Comment by nfalco79** [comment]
I got the same issue. Any news?

**Comment by jobosk** [comment]
I am also experiencing this issue, in the following scenario:

`AbstractEntity {
 A a;
}

Entity extends AbstractEntity {
 B b;
}

Container {
 Entity entity;
}

EntityDTO {
 A a;
 B b;
}

ContainerDTO {
 EntityDTO entityDTO;
}`

I've compressed the logic in the following method:

`private static Container convert(final ContainerDTO containerDTO) {

    final ModelMapper containerMapper = new ModelMapper();
    final TypeMap<ContainerDTO, Container> containerTypeMap =
        containerMapper.createTypeMap(ContainerDTO.class, Container.class);

    final ModelMapper contentMapper = new ModelMapper();
    contentMapper.createTypeMap(EntityDTO.class, Entity.class);

    containerTypeMap.addMappings(m -> m.using(
        ctx -> contentMapper.map(ctx.getSource(), Entity.class)
    ).map(ContainerDTO::getEntityDTO, Container::setEntity));

    return containerMapper.map(containerDTO, Container.class); // ERROR
  }`

Which gives the following error:

`...
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Failed to instantiate instance of destination AbstractEntity. Ensure that AbstractEntity has a non-private no-argument constructor.`

Is this a known problem?
Am I missing something?
