### ISSUE TITLE
Unable to map an object containing a List of objects

### ISSUE THREAD

**Issue by ugo-fl** [modelmapper/modelmapper#403]
Here are the source objects :

```java
import java.util.List;

public class Obj1 {
	private List<Obj2> obj2;

	public List<Obj2> getObj2() {
		return obj2;
	}

	public void setObj2(List<Obj2> obj2) {
		this.obj2 = obj2;
	}
	
	
}
```

```java
public class Obj2 {
	private String test;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}

}
```

Here are the destination objects :

```java
import java.util.ArrayList;
import java.util.List;

public class Obj1DEST {
	private List<Obj2DEST> obj2;

	public List<Obj2DEST> getObj2() {
		if (obj2 == null)
			this.obj2 = new ArrayList<Obj2DEST>();
		return obj2;
	}

}
```

```java
public class Obj2DEST {
	private String test;

	public String getTest() {
		return test;
	}

	public void setTest(String test) {
		this.test = test;
	}
}
```

And the test :

```java
import java.util.ArrayList;
import java.util.List;

import org.modelmapper.ModelMapper;
import org.modelmapper.config.Configuration;
import org.modelmapper.config.Configuration.AccessLevel;

public class Test {
	public static void main(String[] args) {
		ModelMapper modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setFieldAccessLevel(AccessLevel.PRIVATE).setFieldMatchingEnabled(true).setFieldAccessLevel(Configuration.AccessLevel.PACKAGE_PRIVATE)
		.setMethodAccessLevel(Configuration.AccessLevel.PACKAGE_PRIVATE);
		
		Obj1 o1 = new Obj1();
		Obj2 o2 = new Obj2();
		o2.setTest("TEST");
		List<Obj2> o2s = new ArrayList<Obj2>();
		o2s.add(o2);
		o1.setObj2(o2s);
		
		Obj1DEST o1dest = modelMapper.map(o1, Obj1DEST.class);
		System.out.println(o1dest.getObj2().get(0));
	}
}
```

**Comment by UgoFlamarion** [comment]
Another weird thing -> if I add a setter to my Obj1DEST and then add the following :

```java
modelMapper.createTypeMap(Obj1.class, Obj1DEST.class);
modelMapper.getTypeMap(Obj1.class, Obj1DEST.class).addMappings(mapper -> mapper.map(src -> src.getObj2(), (dest, v) -> dest.setObj2((List<Obj2DEST>) v)));
```

It works like a charm. But then if I change it to :

```java
modelMapper.getTypeMap(Obj1.class, Obj1DEST.class).addMappings(mapper -> mapper.map(src -> src.getObj2(), (dest, v) -> dest.getObj2().addAll((List<Obj2DEST>) v)));
```

I get an exception :

> Exception in thread "main" org.modelmapper.internal.ErrorsException
> 	at org.modelmapper.internal.Errors.toException(Errors.java:254)
> 	at org.modelmapper.internal.ReferenceMapExpressionImpl.map(ReferenceMapExpressionImpl.java:71)
> 	at org.modelmapper.internal.ConfigurableMapExpressionImpl.map(ConfigurableMapExpressionImpl.java:68)
> 	at Test.lambda$0(Test.java:19)
> 	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266)
> 	at Test.main(Test.java:19)

**Comment by dlakatos847** [comment]
Similar issue here. I try to map JPA entity to JAXB DTO, where there is no setter generated for `java.util.Set` and `java.util.List` types due to the JAXB standard.

```
myMap.addMappings(mapper -> mapper.<Set<String>>map(src -> src.getAllFormats(), (dst, v) -> dst.getFormats().addAll(v)));
```
throws
```
...
Caused by: org.modelmapper.internal.ErrorsException
	at org.modelmapper.internal.Errors.toException(Errors.java:254)
	at org.modelmapper.internal.ReferenceMapExpressionImpl.map(ReferenceMapExpressionImpl.java:71)
	at org.modelmapper.internal.ConfigurableConditionExpressionImpl.map(ConfigurableConditionExpressionImpl.java:65)
	at com.oracle.consulting.promofw.config.ModelConfiguration.lambda$28(ModelConfiguration.java:100)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266)
...
```
Is this a bug?

**Comment by chhsiao90** [comment]
The `setFieldMatchingEnabled` must be enabled while there is not setter in the destination object, and the `setFieldAccessLevel` must be set correctly so modelmapper can access the field.

For example, we must set `AccessLevel.PRIVATE` if we have private fields.

**Comment by sai-sdocs** [comment]
I am also facing the similar issue which @ugo-fl mentioned. Is there any concrete solution available for this issue? I tried different ways but not able to get the source list values included in the destination but it only replacing the values. Please let me know if any leads on how can I proceed ahead.

**Comment by SaiKoushikAddanki** [comment]
I am also facing the similar issue which @ugo-fl mentioned. Is there any concrete solution available for this issue? I tried different ways but not able to get the source list values included in the destination but it only replacing the values. @chhsiao90  Please let me know if any leads on how can I proceed ahead.
