### ISSUE TITLE
modelmapper is using JDK-internal API

### ISSUE THREAD

**Issue by honzirek** [modelmapper/modelmapper#426]
If I use extend configuration (e.g. method skip in PropertyMap), then I get Exception when using on WildFly 14.

The problem is, that WildFly is by default excluding JDK-internal API. Then I have to manually add <module name="jdk.unsupported" /> into jboss-deployment-structure.xml as a workaround.

Using an JDK-internal API is a bad practice.  Would it be possible to remove this dependency from modelmpper? I guess it is because of sun.reflect.Reflection.

Thank you!

**Comment by notarmara** [comment]
We are using jdk 13 and ModelMapper 2.3.6
I'm writing just to ask you to solve this as soon as possible.
Thank you

org.modelmapper.internal.objenesis.ObjenesisException: **java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory**

org.modelmapper.ConfigurationException: ModelMapper configuration errors:

 1) Failed to configure mappings

1 error

at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:244) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:96) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:92) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:124) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:113) ~[modelmapper-2.3.6.jar:?]
...
Caused by: java.lang.NullPointerException
at org.modelmapper.internal.ExplicitMappingBuilder$ExplicitMappingInterceptor.access$000(ExplicitMappingBuilder.java:304) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.ExplicitMappingBuilder.createAccessorProxies(ExplicitMappingBuilder.java:287) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.ExplicitMappingBuilder.createProxies(ExplicitMappingBuilder.java:277) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:266) ~[modelmapper-2.3.6.jar:?]
at org.modelmapper.PropertyMap.configure(PropertyMap.java:386) ~[modelmapper-2.3.6.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]

**Comment by bekwam** [comment]
I'm getting this with 2.3.8 and Java 11.0.8_10.  Here's a code snippet throwing the exception.  It's steering a pair of JPA entities into a flattened DTO.

`        
modelMapper.typeMap(User.class, UserDTO.class).addMappings(mapper -> {
            mapper.map(src -> src.getUsername(), UserDTO::setUsername);
            mapper.map(src -> src.getAudit().getCreatedOn(), UserDTO::setCreatedOn);
            mapper.map(src -> src.getAudit().getCreatedBy(), UserDTO::setCreatedBy);
        });
`

**Comment by chhsiao90** [comment]
Can you check if latest modelmapper can reproduce this issue? Thanks!

**Comment by richyclarke** [comment]
Still happenning on Wildfly 21 and ModelMapper 2.4.0

**Comment by mfdewit** [comment]
Same problem on ModelMapper 2.4.3 when using a TypeMap  (WildFly Full 24.0.1.Final on Java 13). Without TypeMap it is working fine. 

Caused by: java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory from [Module "deployment.ROOT.war" from Service Module Loader]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:377)
    at deployment.ROOT.war//org.modelmapper.internal.objenesis.instantiator.sun.SunReflectionFactoryHelper.getReflectionFactoryClass(SunReflectionFactoryHelper.java:60)
