### ISSUE TITLE
Mapping an jackson ArrayNode results in a NullPointerException

### ISSUE THREAD

**Issue by Weissger** [modelmapper/modelmapper#447]
Hi I'm trying to use modelmapper to map changes sent via patch request from my DTOs to my DAOs. To archive this I'm using generic jackson JsonNode objects. This works rather good. Unfortunatly mapping ArrayNodes to lists fails with an Nullpointer. 

**affected version:** 2.3.2
**stack trace**
```Exception in thread "main" org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping com.fasterxml.jackson.databind.node.ObjectNode to Scratch$Test

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:447)
	at Scratch.main(scratch_4.java:58)
Caused by: java.lang.NullPointerException
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveAccessorsFromValueReader(PropertyInfoSetResolver.java:80)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveAccessors(PropertyInfoSetResolver.java:71)
	at org.modelmapper.internal.TypeInfoImpl.getAccessors(TypeInfoImpl.java:59)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:168)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:224)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:106)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:88)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:73)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:128)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:102)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:112)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	... 3 more
```
**scratch code**
```import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.modelmapper.ModelMapper;
import org.modelmapper.jackson.ArrayNodeToCollectionConverter;
import org.modelmapper.jackson.CollectionToArrayNodeConverter;
import org.modelmapper.jackson.JsonNodeValueReader;
import org.modelmapper.jackson.PrimitiveJsonNodeConverter;

import java.io.IOException;
import java.util.List;

class Scratch {

    static class Test {
        private String stringVal;
        private List<String> someList;

        public Test() {
        }

        public Test(String stringVal, List<String> someList) {
            this.stringVal = stringVal;
            this.someList = someList;
        }

        public String getStringVal() {
            return stringVal;
        }

        public void setStringVal(String stringVal) {
            this.stringVal = stringVal;
        }

        public List<String> getSomeList() {
            return someList;
        }

        public void setSomeList(List<String> someList) {
            this.someList = someList;
        }
    }

    public static void main(String[] args) throws IOException {
        
        Test test = new Test();
        ObjectMapper objectMapper = new ObjectMapper();
        JsonNode node = objectMapper.readTree("{\"stringVal\": \"something\", \"someList\": [\"2\",\"3\"]}");
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().addValueReader(new JsonNodeValueReader());
        modelMapper.getConfiguration().getConverters().add(0, new PrimitiveJsonNodeConverter());
        modelMapper.getConfiguration().getConverters().add(0, new ArrayNodeToCollectionConverter());
        modelMapper.getConfiguration().getConverters().add(0, new CollectionToArrayNodeConverter(objectMapper));
        modelMapper.map(node, test);
    }
}
```
The same exception is thrown when mapping into a new object `modelMapper.map(node, Test.class);`

I have looked into the [documentation of the jackson integration](http://modelmapper.org/user-manual/jackson-integration/) and couldn't find anything regarding arrays. Did I misconfigure or misuse anything regarding the modelmapper or could this be a bug? Also could this be related to Issue #335? Thanks

**Comment by tlark** [comment]
I am seeing this exact same thing.  I'm evaluating whether to use ModelMapper or not, so can someone tell me the timeframe when this issue will be addressed?  

The issue has been open for 20+ months with no activity.

**Comment by techanon** [comment]
This issue is still a problem using 3.1.0. I am also getting an NPE when trying to map a json array (an optionally empty one in my use case).

Upon investigation, it appears to be caused by the fact that the JsonNodeValueReader returns _null_ if the JsonNode is not an object (such as an array) in this method
https://github.com/modelmapper/modelmapper/blob/338369bf7afc75f2b4360f6d68a17ee60dc8c56b/extensions/jackson/src/main/java/org/modelmapper/jackson/JsonNodeValueReader.java#L80-L86

and on line 80 here:
https://github.com/modelmapper/modelmapper/blob/338369bf7afc75f2b4360f6d68a17ee60dc8c56b/core/src/main/java/org/modelmapper/internal/PropertyInfoSetResolver.java#L78-L82
it is explicitly expecting the `valueReader.memberNames` result to be an `Iterable` due to it being in-lined within a for loop. Retuning null from that method will toss an NPE.

I'm not sure the reason why the `memberNames` method on the `JsonNodeValueReader` class needs to return null at all.  
The result of the `fieldNames` call always returns a collection of some kind regardless of the node type, so it shouldn't need to check for `isObject` at all.

Additionally I would add that the `memberNames` call in the resolver class should be null checked against to skip the loop if a custom `ValueReader` returns null from that method.

Also the same thing applies to `ValueWriter` part as well.

**Comment by Tamir1205** [comment]
any updates?

**Comment by WatchdataGitHub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Tamir1205** [comment]
i am encountering with the same problem in 3.2.0 version(java 17, spring boot 3.2.4)
