### ISSUE TITLE
Explicit mapping to primitive destination fails with NPE

### ISSUE THREAD

**Issue by jmcnair-intermx** [modelmapper/modelmapper#480]
public class PrimitiveTest {
	private ModelMapper mapper = new ModelMapper();

	@Test
	void primitiveDestination() {
		mapper.typeMap(Primitive.class, Primitive.class).addMapping(Primitive::getInt, Primitive::setInt);
	}

	private static class Primitive {
		public int getInt() {
			return 1;
		}
		public void setInt(int someInt) {
		}
	}
}

In the above test, addMapping() fails with:
java.lang.NullPointerException
	at org.modelmapper.internal.ReferenceMapExpressionImpl.map(ReferenceMapExpressionImpl.java:68)
	at org.modelmapper.internal.TypeMapImpl.addMapping(TypeMapImpl.java:260)
	at org.modelmapper.test.PrimitiveTest.primitiveDestination(PrimitiveTest.java:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by jmcnair-intermx** [comment]
Has anyone else seen this?

**Comment by gutors** [comment]
Having the same issue here, mapping Integer to int, and LocalDateTime to LocalDateTime.

Started happening since i upgraded from wildfly10 to wildfly 17 and javaEE7 to javaEE8.

**Comment by martinth** [comment]
I just into this and figured out and I have more information to share.

- It seems to happen when the source getter returns a Boxed value (say `Boolean` and the setter accepts a primitive `boolean`
- It does not happen when running Java 11 (OpenJDK 11.0.6 for me) but it happens when running with Java 14 (OpenJDK 14.0.2 for me)

Here is a testcase for now

```
package org.modelmapper.bugs;

import org.modelmapper.AbstractTest;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;

@Test
public class GH480 extends AbstractTest {
  static class Source {
    public Boolean getSourceBool() {
      return sourceBool;
    }

    Boolean sourceBool;

  }

  static class Dest {
    public void setTargetBool(boolean targetBool) {
      this.targetBool = targetBool;
    }

    boolean targetBool;

  }

  public void test() {
    modelMapper.typeMap(Source.class, Dest.class).addMapping(Source::getSourceBool, Dest::setTargetBool);

    Source source = new Source();
    source.sourceBool = true;

    Dest d = modelMapper.map(source, Dest.class);

    assertEquals(d.targetBool, true);
  }
}

```

It runs fine on Java 11 but fails on Java 14. If you change the signature of setTargetBool to `setTargetBool(Boolean targetBool)` it works for both cases.
