### ISSUE TITLE
Regression: skipping primitive properties fails with NullPointerException

### ISSUE THREAD

**Issue by fernanfs** [modelmapper/modelmapper#511]
The issue discussed in #242 reoccurs in 2.3.5.

When running the example mentioned in #242, I' see the following exception:
```
Exception in thread "main" java.lang.NullPointerException
	at org.modelmapper.internal.ReferenceMapExpressionImpl.skip(ReferenceMapExpressionImpl.java:85)
	at org.modelmapper.internal.ConfigurableConditionExpressionImpl.skip(ConfigurableConditionExpressionImpl.java:71)
	at com.example.Main.lambda$thisOneDoesNotWork$1(Main.java:33)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266)
	at com.example.Main.thisOneDoesNotWork(Main.java:33)
	at com.example.Main.main(Main.java:10)
```

Is there a known workaround for that?

**Comment by redfast00** [comment]
I believe I have the exact same issue on 2.3.7:

```
java.lang.NullPointerException
	at org.modelmapper.internal.ReferenceMapExpressionImpl.skip(ReferenceMapExpressionImpl.java:85)
	at org.modelmapper.internal.ConfigurableConditionExpressionImpl.skip(ConfigurableConditionExpressionImpl.java:71)
	at com.redacted.redacted.lambda$someToSomeEntity$11(RedactedClass.java:78)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266)
```

**Comment by antemo** [comment]
I have same problem with `boolean` setter in 2.3.7.
This might be due to Java version, since same code that doesn't work with JDK 14 or JDK 12 works fine with JDK 1.8

**Comment by Alex217** [comment]
I am using ModelMapper v2.3.7 with JDK 11 and I also need the possibility to skip a setter with a primitive `boolean` parameter. Currently ModelMapper throws a `NullPointerException`.

**Comment by jo-ka** [comment]
This is most definitely related to https://github.com/modelmapper/modelmapper/issues/480. The same workaround I [posted](https://github.com/modelmapper/modelmapper/issues/480#issuecomment-707775121) there also works for skipping (call `skip` in the overridden method instead of `map`).
