### ISSUE TITLE
Plans to support for Java Records (Java-14)?

### ISSUE THREAD

**Issue by namannigam** [modelmapper/modelmapper#546]
Quoting from a [StackOverflow Q&A ](https://stackoverflow.com/questions/62455515/how-can-i-use-java-records-as-dto-with-modelmapper), the current version 2.3.8 doesn't seem to support java `record` classes.

The minimal code sample used to test this (quoting the link)

```
public record UserDto(String firstName,
                      String lastName,
                      String email,
                      String imageUrl) {}
```

``` User post = modelMapper.map(userDto, User.class);```

**Comment by briangoetz** [comment]
Records _must_ be instantiated through their constructor.  In the preview as of Java 14, the usual `Unsafe` tricks may work, but these will stop working before records become a permanent feature.  Frameworks will need to examine a class to see if it is a record (`Class::isRecord`) and if so, find the canonical constructor (guaranteed to be there) through reflection.

**Comment by chhsiao90** [comment]
Reference: https://github.com/youribonnaffe/jackson-databind/commit/072189b72509ebc8abc1c0feee93d6ad393f8d90

**Comment by bzitzow** [comment]
Bump. Any updates on this as a supported feature?

**Comment by VadymRoganin** [comment]
What about now? I miss this in my current project.

**Comment by isaacchircop** [comment]
Any updates on current status or plans to support this please?

**Comment by chhsiao90** [comment]
There is no update on this issue.

ModelMapper can easily support `Record -> POJO` by implementing [ValueReader](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/spi/ValueReader.java).

But it's tricky to support `POJO/Record -> Record`, because the record is an immutable class, and ModelMapper is not supporting constructor based destination.

I can implement `Record -> POJO`  but leaving `POJO/Record -> Record`  unimplemented, I don't have any plan to support constructor based destination.

[mapstruct](https://github.com/mapstruct/mapstruct) might be an option for you if it blocks you. Sorry for the inconvenience.

**Comment by okaponta** [comment]
@chhsiao90 
Hi, I just implemented `Record -> POJO` for my local app.
Do you have any plan to support `Record -> POJO` ?

If I can add class for `Record -> POJO`, I am thinking to make Pull Request for adding the feature.
maybe adding class `org.modelmapper.internal.valueaccess.RecordValueReader`

The implemented codes are below.

```RecordValueReader.java
import org.modelmapper.internal.Errors;
import org.modelmapper.spi.ValueReader;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class RecordValueReader implements ValueReader<Record> {
    @Override
    public Object get(Record record, String memberName) {
        Field field = matchField(record, memberName);
        if (field != null) {
            try {
                return field.get(record);
            } catch (IllegalAccessException e) {
                throw new Errors().addMessage(e, "Cannot get the member").toMappingException();
            }
        }
        return null;
    }

    @Override
    public Member<Record> getMember(Record record, String memberName) {
        Field field = matchField(record, memberName);
        Class<?> type = field != null ? field.getClass() : Record.class;
        return new Member<>(type) {
            @Override
            public Object get(Record source, String memberName) {
                return RecordValueReader.this.get(source, memberName);
            }
        };
    }

    @Override
    public Collection<String> memberNames(Record record) {
        Field[] fields = record.getClass().getDeclaredFields();
        List<String> memberNames = new ArrayList<>(fields.length);
        for (Field field : fields) {
            field.setAccessible(true);
            memberNames.add(field.getName());
        }
        return memberNames;
    }

    private Field matchField(Record source, String memberName) {
        for (Field field : source.getClass().getDeclaredFields()) {
            field.setAccessible(true);
            if (memberName.equalsIgnoreCase(field.getName()))
                return field;
        }
        return null;
    }
}
```

**Comment by salarai** [comment]
are there any updates on supporting records?

**Comment by Husan** [comment]
Are there any updates on supporting records?

**Comment by AugustoRavazoli** [comment]
Are there updates?

**Comment by srirv** [comment]
Any update?

**Comment by okaponta** [comment]
made PR supporting Record -> POJO
https://github.com/modelmapper/modelmapper/pull/715

**Comment by marcosjrpb** [comment]
Any update on this? Thanks!

**Comment by okaponta** [comment]
for Record -> POJO, use this repository.
https://github.com/modelmapper/modelmapper-module-record

**Comment by messelmanibrahim** [comment]
Hello,

Any recommandations for POJO-> Record ?

I am getting back : 

Ensure that MYRECORD has a non-private no-argument constructor.

Caused by: java.lang.NoSuchMethodException: MYRECORD .<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:386)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:589)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:422)

**Comment by WatchdataGitHub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by evil-face** [comment]
Still a huge need!

**Comment by sergey-morenets** [comment]
> for Record -> POJO, use this repository. https://github.com/modelmapper/modelmapper-module-record

Unfortunately it doesn't work. Please, look at https://github.com/modelmapper/modelmapper-module-record/issues/1

**Comment by Hwan0518** [comment]
Any update?

**Comment by pmcnsr** [comment]
Any update to pojo -> record? Still important

**Comment by qdev0** [comment]
Agi has come and still no pojo to record...

**Comment by FdHerrera** [comment]
Guess still no updates on this, is this the correct issue to follow up?

**Comment by WatchdataGitHub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kendarorg** [comment]
I suppose it should be solved with the new modifications to https://github.com/modelmapper/modelmapper-module-record with the implementation of the constructor injector new setting

**Comment by chhsiao90** [comment]
I'd say it was only supported partially. Mapping something like `class User(name, phone) into record UserRecord(user, phone)` is supported, but deep mapping like `class User(addressCity) into record UserRecord(AddressRecord)` is not supported yet.

**Comment by saranshbansal** [comment]
This is giving a heavy competition to gta6. Let's see who'll win.

**Comment by ayevexy** [comment]
I didn't even remembered this discussion lol

**Comment by WatchdataGitHub** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
