### ISSUE TITLE
Fails to run with Java 15

### ISSUE THREAD

**Issue by dantheperson** [modelmapper/modelmapper#568]
Java 13 is long out of support, so we are updating to Java 15, but at runtime modelmapper throws this error:

`Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:195)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:176)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:162)
	at org.modelmapper.internal.asm.ClassReader.<init>(ClassReader.java:283)
	at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:255)
	at org.modelmapper.PropertyMap.configure(PropertyMap.java:386)
`

**Comment by dantheperson** [comment]
Sorry is see this is a dupe of #564
