### ISSUE TITLE
JDK16 & mappings with fields of type Instant

### ISSUE THREAD

**Issue by kleanthis** [modelmapper/modelmapper#610]
I've posted this in the response to a previous issue on JDK16, but have not seen any response. Everything else equal on my end, I am having issues as described below. I am wondering if I am missing something, or if indeed this is a known issue?

---

> ModelMapper v2.4.1 was just released including the fix.

I am still seeing an exception when the mapping applied to a field that is of type `Instant`. Is it just me?

```
...
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not "opens java.time" to unnamed module @c730b35
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171) ~[na:na]
	at org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo.<init>(PropertyInfoImpl.java:58) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoRegistry.fieldPropertyFor(PropertyInfoRegistry.java:118) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoResolver$1.propertyInfoFor(PropertyInfoResolver.java:38) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoResolver$1.propertyInfoFor(PropertyInfoResolver.java:35) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:139) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:113) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveAccessors(PropertyInfoSetResolver.java:73) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.TypeInfoImpl.getAccessors(TypeInfoImpl.java:59) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:170) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:232) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:108) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:90) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:75) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:128) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:102) ~[modelmapper-2.4.1.jar:na]
	at org.modelmapper.ModelMapper.typeMap(ModelMapper.java:347) ~[modelmapper-2.4.1.jar:na]
...
```

_Originally posted by @kleanthis in https://github.com/modelmapper/modelmapper/issues/603#issuecomment-826345233_

**Comment by chhsiao90** [comment]
It looks like it's different issue of #603.

Have you tried https://github.com/modelmapper/modelmapper-module-java8 for mapping jsr310 types?

**Comment by kleanthis** [comment]
With everything else equal, going from JDK15.0.1 to JDK16, I was getting the error mentioned above. 

In Gradle I added:
```
implementation 'org.modelmapper:modelmapper-module-jsr310:1.2.2'
```

and for configuration:
```
final var modelMapper = new ModelMapper();
modelMapper.registerModule(new Jsr310Module());
```
It made no difference, i.e. same error. 

I did some more digging and noticed that happening in cases where ModelMapper is configured to use `AccessLevel.PRIVATE`, i.e.:
```
modelmapper.getConfiguration()
    .setFieldMatchingEnabled(true)
    .setFieldAccessLevel(AccessLevel.PRIVATE);
```

Changing over the field access level to `AccessLevel.PUBLIC`, makes the problem go away and there doesn't seem to be a need to register the `Jsr310Module`.

I'll leave that with you to close this ticket if that's what you were expecting. Hopefully, it will help someone when upgrading.

**Comment by chhsiao90** [comment]
HI @kleanthis -

Thanks for reporting the issue, it should work with Jsr310Module.
Can you provide the source and destination bean so I can try to reproduce the issue? Thanks.

**Comment by kleanthis** [comment]
Apologies — I cannot share them. Something I failed to mention is that I am using Lombok — however as I said the only change (in my case) was changing `AccessLevel`.
