### ISSUE TITLE
A test of version 2.4.2 failed on JDK16

### ISSUE THREAD

**Issue by zcglisp** [modelmapper/modelmapper#613]
I'm sorry to bother you, but org.modelmapper.bugs.GH550#shouldSupportHashMapSubClass failed on JDK16.

Is it possible not to call the method setAccessible(true) when the package name starts with "java." or "javax."?
I found six calls to the method "setAccessible" in ModelMapper 2.4.2

According to the JEP 396 https://openjdk.java.net/jeps/396 
Code that uses reflection to access private fields of exported java.* APIs will no longer work by default.
For example, the method java.lang.reflect.AccessibleObject#setAccessible(boolean) 

Here is the error when run GH550#shouldSupportHashMapSubClass :

org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping org.modelmapper.bugs.GH550$Source to org.modelmapper.bugs.GH550$Destination

1 error

	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:406)
	at org.modelmapper.bugs.GH550.shouldSupportHashMapSubClass(GH550.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.Set java.util.AbstractMap.keySet accessible: module java.base does not "opens java.util" to unnamed module @1ef7fe8e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo.<init>(PropertyInfoImpl.java:58)
	at org.modelmapper.internal.PropertyInfoRegistry.fieldPropertyFor(PropertyInfoRegistry.java:118)
	at org.modelmapper.internal.PropertyInfoResolver$1.propertyInfoFor(PropertyInfoResolver.java:38)
	at org.modelmapper.internal.PropertyInfoResolver$1.propertyInfoFor(PropertyInfoResolver.java:35)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:139)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:130)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:130)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveProperties(PropertyInfoSetResolver.java:113)
	at org.modelmapper.internal.PropertyInfoSetResolver.resolveAccessors(PropertyInfoSetResolver.java:73)
	at org.modelmapper.internal.TypeInfoImpl.getAccessors(TypeInfoImpl.java:59)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:170)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchSource(ImplicitMappingBuilder.java:232)
	at org.modelmapper.internal.ImplicitMappingBuilder.matchDestination(ImplicitMappingBuilder.java:108)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:90)
	at org.modelmapper.internal.ImplicitMappingBuilder.build(ImplicitMappingBuilder.java:75)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:128)
	at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:102)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:112)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	... 26 more

Thanks a lot

**Comment by chhsiao90** [comment]
Hi @zcglisp - Can you provide example source code for demonstrating the issue? Thanks!

**Comment by zcglisp** [comment]
I'm running ModelMapper's own unit test. The class name is: org.modelmapper.bugs.GH550 , the method is shouldSupportHashMapSubClass , ModelMapper's version 2.4.2

**Comment by chhsiao90** [comment]
ModelMapper v2.4.3 released.
