### ISSUE TITLE
Mapping argument type mismatch error since 2.4.0

### ISSUE THREAD

**Issue by Roman-Skripka** [modelmapper/modelmapper#615]
Mapping worked fine with 2.3.9, but with changes in 2.4.0 it fails. Stacktrace below is for current master version.

```
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Converter org.modelmapper.internal.converter.MergingCollectionConverter@3a32f30e failed to convert org.hibernate.collection.internal.PersistentBag to java.util.List.

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:80)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:495)
	***
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Failed to set value 'class SomeAdminModel {
    class SomeBaseModel {
        class SomeRootModel {
            ...
        }
        id: 6
        year: null
        ...
    }
    aaa: null
    bbb: null
}' on models.AbcAdminModel.setSome()

1 error
	at org.modelmapper.internal.Errors.toMappingException(Errors.java:258)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:128)
	at org.modelmapper.internal.MappingContextImpl.getParentDestination(MappingContextImpl.java:325)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:230)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:187)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:114)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:59)
	at org.modelmapper.internal.converter.MergingCollectionConverter.convert(MergingCollectionConverter.java:31)
	at org.modelmapper.internal.MappingEngineImpl.convert(MappingEngineImpl.java:306)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:109)
	at org.modelmapper.internal.MappingEngineImpl.setDestinationValue(MappingEngineImpl.java:245)
	at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:187)
	at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:114)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71)
	... 159 common frames omitted
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.modelmapper.internal.PropertyInfoImpl$MethodMutator.setValue(PropertyInfoImpl.java:126)
	... 173 common frames omitted
```

I map an object with list field to another object with list field. Each list has different type and it fails during mapping of the field of type 'SomeAdminModel'.
I took a look in the debugger and for some reason it tries to set an unmapped object and this produces "argument type mismatch" error above.

my mapper configuration is as following:
```
modelMapper.getConfiguration().setFieldMatchingEnabled(true).setMatchingStrategy(MatchingStrategies.STRICT).setFieldAccessLevel(
            Configuration.AccessLevel.PRIVATE).setUseOSGiClassLoaderBridging(true);
```

**Comment by chhsiao90** [comment]
Hi @Roman-Skripka ,

Can you provides the source and destination model for reproducing this issue? Thanks!

**Comment by kelvinsleonardo** [comment]
Any solution?

**Comment by husseyd** [comment]
Same for us. Stuck on 2.3.9 which prevents upgrade to JDK > 11.0.10

**Comment by lazaro3487** [comment]
Hello. Is there any update about this problem? I have updated my modelmapper version from 2.3.9 to 3.1.0 and my mapping layer is also broken.

**Comment by DagleAnderson** [comment]
I've been working with modelmapper for 3 years, using version 2.3.0. But as time passed and my project grew, the construction time grew along with it. this gave me a smaller output. This year I updated the version to 3.0.0. But all the mappings stopped working and now I just don't know what I can do to improve my project.

**Comment by Spookyguy** [comment]
Same Problem here. After moving from 2.3.9 to any version higher than that, i got exactly the same exception as described above. Trying to upgrade Java to JVM 17 using version 2.3.9 does not work either. Are there any updates on this issue?

**Comment by marcioggs** [comment]
Same problem here in v3.1.0, and I can see in the debugger that a String is trying to be mapped to an object via reflection.

The exception is thrown at line 124 of PropertyInfoImpl at version v3.1.0.

https://github.com/modelmapper/modelmapper/blob/251772e790fe6b0799db052681c82bea0e760b43/core/src/main/java/org/modelmapper/internal/PropertyInfoImpl.java#L124

Info from debugger:
```
member = public void com.mypackage.ClassADto.setClassBDto(com.mypackage.ClassBDto)
value = "com.mypackage.ClassB@44d62b68"          // String from toString(), not the object
```
