### ISSUE TITLE
org.modelmapper.MappingException: ModelMapper mapping errors:

### ISSUE THREAD

**Issue by khursid-jbl** [modelmapper/modelmapper#645]
org.modelmapper.MappingException: ModelMapper mapping errors:
 1) Converter org.modelmapper.internal.converter.MapConverter@6d60359c failed to convert java.util.HashMap to java.util.Map.
 1 error
 	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
 	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:81)
 	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
 	at org.modelmapper.ModelMapper.map(ModelMapper.java:447)
 	at com.oms.OrderFullMapper.mapTo(OrderFullMapper.java:150)
 	at com.oms.ServiceImpl.lambda$getOrder$1(ServiceImpl.java:291)
 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.lang.ClassCastException: null

We are facing the above errors on production since last couple of days. We had no change in the code.  The issue is intermittent and exists only in some of the containers of a service.

Can anybody tell what can be the probable issue and resolution?

**Comment by irinatarn** [comment]
Same here - our production started showing 
org.modelmapper.MappingException: ModelMapper mapping errors:
....
Caused by: java.lang.ClassCastException

No code change, no new deployment.

**Comment by chhsiao90** [comment]
see #606

Feel free if you still have issues.
