### ISSUE TITLE
1) Failed to instantiate instance of destination java.util.UUID. Ensure that java.util.UUID has a non-private no-argument constructor.

### ISSUE THREAD

**Issue by sheiy** [modelmapper/modelmapper#660]
org.modelmapper.MappingException: ModelMapper mapping errors:

1) Failed to instantiate instance of destination java.util.UUID. Ensure that java.util.UUID has a non-private no-argument constructor.
.....
Caused by: java.lang.NoSuchMethodException: java.util.UUID.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.modelmapper.internal.MappingEngineImpl.instantiate(MappingEngineImpl.java:336)

**Comment by chhsiao90** [comment]
It looks like we need an `UuidConverter` to support UUID out of box.

**Comment by niccccccccer** [comment]
I would like to work on this issue to add an UuidConverter which can support UUID.
