### ISSUE TITLE
ModelMapper mapping to POJO -> Hibernate Lazy Proxy Object and session closed

### ISSUE THREAD

**Issue by corbs9** [modelmapper/modelmapper#685]
There is currently an issue when mapping a simple POJO to another object which is retrieved via Hibernate that has lazy instance variables of type `Collection<T> `and the session is closed. 

Using the `NonMergingCollectionConverter`, the expected behaviour should be to obtain the type of the destination, and map the source to the destination using the class type. Instead, ModelMapper attempts to retrieve an object from the Collection and use that to map from the source for whatever reason. 

A proposal would be to change the following:
```
for (Iterator<Object> iterator = Iterables.iterator(source); iterator.hasNext(); index++) {
      Object sourceElement = iterator.next();
      Object element = null;
      if (originalDestination != null)
        element = Iterables.getElement(originalDestination, index);
      if (sourceElement != null) {
        MappingContext<?, ?> elementContext = element == null
            ? context.create(sourceElement, elementType)
            : context.create(sourceElement, element);
        element = context.getMappingEngine().map(elementContext);
      }
      destination.add(element);
    }
```

to...
```
MappingContext<?, ?> elementContext = context.create(sourceElement, elementType);
for (Iterator<Object> iterator = Iterables.iterator(source); iterator.hasNext(); index++) {
      Object sourceElement = iterator.next();
      Object element = null;
      if (sourceElement != null) {
        MappingContext<?, ?> elementContext = context.create(sourceElement, elementType);
        element = context.getMappingEngine().map(elementContext);
      }
      destination.add(element);
    }
```

(I haven't tested this for compilation errors as I'm doing it by hand in this editor, but we have had to create a `ReplacingCollectionConverter` which essentially does this and replace the `NonMergingCollectionConverter` within ModelMapper to fix it). 

It actually doesn't make sense to create the context from the element in the destination in this scenario as we will be replacing everything anyway!

```
org.hibernate.LazyInitializationException: failed to lazily initialize a collection, could not initialize proxy - no Session

	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:612)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:162)
	at org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:371)
	at org.modelmapper.internal.util.Iterables.getElementFromCollection(Iterables.java:106)
	at org.modelmapper.internal.util.Iterables.getElement(Iterables.java:78)
	at org.modelmapper.internal.converter.NonMergingCollectionConverter.convert(NonMergingCollectionConverter.java:53)
	at org.modelmapper.internal.converter.NonMergingCollectionConverter.convert(NonMergingCollectionConverter.java:31)
```

**Comment by corbs9** [comment]
Closing. Not getting anywhere with this project.
