### ISSUE TITLE
Exception on Android

### ISSUE THREAD

**Issue by avoloshko** [modelmapper/modelmapper#72]
examples / src / main / java / org / modelmapper / projection / example2

doesn't work.

10-08 10:21:38.859: E/AndroidRuntime(14025): FATAL EXCEPTION: main
10-08 10:21:38.859: E/AndroidRuntime(14025): java.lang.RuntimeException: Unable to start activity ComponentInfo{}: org.modelmapper.ConfigurationException: ModelMapper configuration errors:
10-08 10:21:38.859: E/AndroidRuntime(14025): 1) An error occured while building mappings
10-08 10:21:38.859: E/AndroidRuntime(14025): 1 error
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.app.ActivityThread.access$600(ActivityThread.java:153)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.os.Handler.dispatchMessage(Handler.java:99)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.os.Looper.loop(Looper.java:137)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at android.app.ActivityThread.main(ActivityThread.java:5289)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at java.lang.reflect.Method.invokeNative(Native Method)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at java.lang.reflect.Method.invoke(Method.java:525)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at dalvik.system.NativeStart.main(Native Method)
10-08 10:21:38.859: E/AndroidRuntime(14025): Caused by: org.modelmapper.ConfigurationException: ModelMapper configuration errors:
10-08 10:21:38.859: E/AndroidRuntime(14025): 1) An error occured while building mappings
10-08 10:21:38.859: E/AndroidRuntime(14025): 1 error
10-08 10:21:38.859: E/AndroidRuntime(14025):    at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:239)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:176)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
10-08 10:21:38.859: E/AndroidRuntime(14025):    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)

**Comment by chhsiao90** [comment]
Related to 87
