### ISSUE TITLE
Mapping nested generic object with generic

### ISSUE THREAD

**Issue by HVollmilch** [modelmapper/modelmapper#732]
Hi there,

i have a issue mapping a nested generic object. I simplified my problem to the following classes:

```
@Data
public class BaseChild {

    private Long id;

}

@Data
public class Child extends BaseChild {

    private String name;

}

@Data
public class Parent extends BaseParent<Child> {

    private String name;

}

@Data
public class BaseParent<C extends BaseChild> {

    private C child;

}

@Data
public class Message {

    private Long id;

    private String name;

}

```

I defined this mapping:

```
public class Test {

    public static void main(String[] args) {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);

        modelMapper.typeMap(BaseParent.class, Message.class).addMappings(mapper ->
            mapper.map(p -> p.getChild().getId(), Message::setId)
        );
        modelMapper.typeMap(Parent.class, Message.class).includeBase(BaseParent.class, Message.class);

        Child child = new Child();
        child.setName("Child");
        child.setId(5L);

        Parent parent = new Parent();
        parent.setName("Parent");
        parent.setChild(child);

        Message message = modelMapper.map(parent, Message.class);

    }
}
```
This works fine although it would be nice if i dont have to add mappings with includeBase for my base types (is this possible? I have 20+ subtypes and that would be pain...)

My problem begins if i add a generic to BaseChild (even though it has nothing to do with the mapping itself)

`public class BaseChild<T>`
`public class Child extends BaseChild<String>`
`public class BaseParent<C extends BaseChild<?>>`

Then i get the following exception on startup

```
Exception in thread "main" org.modelmapper.internal.ErrorsException
	at org.modelmapper.internal.Errors.toException(Errors.java:253)
	at org.modelmapper.internal.ReferenceMapExpressionImpl.visitSource(ReferenceMapExpressionImpl.java:113)
	at org.modelmapper.internal.ReferenceMapExpressionImpl.map(ReferenceMapExpressionImpl.java:66)
	at org.modelmapper.internal.ConfigurableConditionExpressionImpl.map(ConfigurableConditionExpressionImpl.java:67)
	at com.dreso.master.data.core.mq.test.Test.lambda$main$1(Test.java:18)
	at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:266)
	at com.dreso.master.data.core.mq.test.Test.main(Test.java:17)
```

coming from:
`mapper.map(p -> p.getChild().getId(), Message::setId)`

**Comment by HVollmilch** [comment]
I noticed that it works if i remove the `<?>` from `public class BaseParent<C extends BaseChild>`
