### ISSUE TITLE
Add support for Android

### ISSUE THREAD

**Issue by kbagi** [modelmapper/modelmapper#87]
Basically can't use custom mappings on Android:

Caused by: org.modelmapper.ConfigurationException: ModelMapper configuration errors:
    1) An error occured while building mappings
    1 error
            at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:239)
            at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:176)
            at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
            at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
            at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
            at com.excelpoint.karol.eim.Activities.HomeActivity.onCreate(HomeActivity.java:56)
            at android.app.Activity.performCreate(Activity.java:5104)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
            ... 11 more
     Caused by: java.lang.ExceptionInInitializerError
            at org.modelmapper.internal.ProxyFactory.proxyClassFor(ProxyFactory.java:58)
            at org.modelmapper.internal.ProxyFactory.proxyFor(ProxyFactory.java:81)
            at org.modelmapper.internal.ExplicitMappingBuilder.getSource(ExplicitMappingBuilder.java:204)
            at org.modelmapper.PropertyMap.configure(PropertyMap.java:291)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:161)
            ... 18 more
     Caused by: java.lang.VerifyError: org/modelmapper/internal/cglib/core/ReflectUtils
            at org.modelmapper.internal.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166)
            at org.modelmapper.internal.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
            at org.modelmapper.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
            at org.modelmapper.internal.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
            at org.modelmapper.internal.cglib.core.KeyFactory.create(KeyFactory.java:116)
            at org.modelmapper.internal.cglib.core.KeyFactory.create(KeyFactory.java:108)
            at org.modelmapper.internal.cglib.core.KeyFactory.create(KeyFactory.java:104)
            at org.modelmapper.internal.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)

**Comment by AndroidGecko** [comment]
would be great if this could work on android

**Comment by genemang** [comment]
Is there a beta version or any non-guaranteed code that I could use that will allow me to use ProperyMap's in android?

**Comment by jhalterman** [comment]
@genemang  There's no Android beta support right now. At this point the fastest way to get Android support would be a contribution as I'm tied up with other projects. I can certainly help point someone towards what sort of changes might need to be made. 

In short, there are two areas where a change would be required: in proxy'ing map'ed types and in reading bytecode to learn which mappings a user has defined. When you define a mapping in a PropertyMap, such as:

```
new PropertyMap<Person, PersonDTO>() {
  protected void configure() {
    map().setName(source.getName());
  }
}
```

...ModelMapper generates a proxy class for Person and PersonDTO which allow it to capture the `setName` and `getName` invocations that indicate the mappings you want to declare. These proxies are created by the `ExplicitMappingBuilder` class. ModelMapper also uses [ASM](http://asm.ow2.org/) for reading PropertyMap bytecode to learn additional information about your mapping, and in particular, to detect field mappings. The `ExplicitMappingVisitor` class is an ASM `ClassVisitor` implementation that takes care of this.

For Android/Dex support - we'd need a to add support for generating DEX proxies to `ExplicitMappingBuilder`. We'd also need an ExplicitMappingVisitor the [ASMDEX](http://asm.ow2.org/asmdex-index.html) library's `ClassVisitor`. ExpicitMappingBuilder could then select the appropriate visitor to use based on the type of bytecode to be read.

**Comment by genemang** [comment]
Thanks.  Like you, I’m tied up as well, otherwise I might take a look.  This is a really good mapping library.   Android support would make it superlative.  I do appreciate your feedback.   How long do you think this would take, should someone decide to undertake it?

Gene Mangrum
Nashville, TN

**Comment by jhalterman** [comment]
I have no idea how long it would take. Assuming the ExplicitMappingVisitor impl for DEX is similar to that for JVM bytecode, it probably wouldn't be too bad.

**Comment by xiongtec** [comment]
any update on this issue?

**Comment by jhalterman** [comment]
No work done in this area, but a path forward would possibly involve swapping out Cglib for Bytebuddy, which supports Android/Dex. Cglib is currently used to produce source and destination proxies that help record property mappings inside a `PropertyMap`. We'd also need to add an optional ASM-dex dependency to parse Dex encoded `PropertyMap` impls. ASM is also used to intepret and record property mappings.

**Comment by vittoriocb** [comment]
+1 Waiting for this. Any updates?

**Comment by tommus** [comment]
Version 2.0.0. Cglib replaced with ByteButty but the problem still exists. Any views for change?

**Comment by chhsiao90** [comment]
Thanks for the reminder, I will investigate on this.

**Comment by chhsiao90** [comment]
hi, I'm working on this, and it looks like we need to provide a jar without shaded dependencies. And we cannot support PropertyMap (it involved with class reading), so please use ExpressionMap instead.

I will keep you posted on any further update. I think it can be done at the end of this month.

**Comment by Ditscheridou** [comment]
Hi guys any update here for supporting android/kotlin?

**Comment by tommus** [comment]
@Ditscheridou - AFAIK nothing had changed regarding better support of Android platform. Personally, I did switch to [Map Struct](https://github.com/mapstruct/mapstruct) and I'm happy with my decistion.
