### ISSUE TITLE
Prevent Hibernate lazy loading

### ISSUE THREAD

**Issue by marcelo-lucio-onofre** [modelmapper/modelmapper#97]
Hi, 

Is there any way to avoid Lazy Loading launched by hibernate? With the dozer can create a CustomFieldMapper that manipulates these values​​, but found the ModelMapper much simpler

```
public class MyCustomFieldMapper implements CustomFieldMapper 
{
    public boolean mapField(Object source, Object destination, Object sourceFieldValue, ClassMap classMap, FieldMap fieldMapping) {       

        if (!(sourceFieldValue instanceof PersistentSet)) {
            return false;
        }


        if (((PersistentSet) sourceFieldValue).wasInitialized()) {

            return false;
        }
        destination = null;
        return true;
    }   
}
```

**Comment by vmf** [comment]
Hi there! I'm working on a project that aims to solve common JPA problems when mapping entities to DTOs using ModelMapper. This issue has already been solved on the project. Project link: [JPA Model Mapper](https://github.com/vmf/modelmapper-jpa)

**Comment by marcusvoltolim** [comment]
Using lambda:

`modelMapper.getConfiguration().setPropertyCondition(context -> !(context.getSource() instanceof PersistentCollection))`

**Comment by malkochoglu** [comment]
Is there a way to do it selectively per modelmapper.map(..)? Not globally as discussed? I have a case that I leave the decision to API caller to request nested JPA objects. Let's say if an optional parameter is set to false nested object is null, if true API return nested object as well.

**Comment by micobarac** [comment]
Well, I have the same problem. The proposed condition above didn't work for me.
I still get the error:

`failed to lazily initialize a collection of role: ...`

**Comment by chhsiao90** [comment]
Hi @micobarac ,

Can you provide reproducible code or more information? Thanks.

**Comment by micobarac** [comment]
```java
/**
 * An Account.
 */
@Entity
@Table(name = "account")
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Size(max = 100)
    @Pattern(regexp = Constants.ACCOUNT_REGEX, message = Constants.ACCOUNT_MESSAGE)
    @Column(name = "name", nullable = false)
    private String name;

    @ManyToOne
    private Group group;
    ...
}

/**
 * A Group.
 */
@Entity
@Table(name = "jhi_group")
public class Group implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Size(min = 1, max = 255)
    @Pattern(regexp = Constants.NAME_REGEX, message = Constants.NAME_MESSAGE)
    @Column(name = "name")
    private String name;

    @JsonIgnore
    @ManyToMany(mappedBy = "groups")
    private Set<Account> accounts = new HashSet<>();

    @OneToMany(mappedBy = "group", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<GroupService> services = new HashSet<>();
    ...
}
```

When I try to map **Account** i get from the database to a new **Account** (even though apply the proposed mapper condition), I get:

`failed to lazily initialize a collection of role: group.services`

**Comment by chhsiao90** [comment]
Have you tried the solution mentioned above?

**Comment by micobarac** [comment]
https://github.com/modelmapper/modelmapper/issues/97#issuecomment-814952117

**Comment by chhsiao90** [comment]
Do you have full stacktrace and example/reproducible code?

**Comment by micobarac** [comment]
No, unfortunatelly not. It's a huge project with big and interconnected entities. The point is that the solution above solves the problem of preventing mapper to map the persistent collections, but nevertheless, it triggers those lazy loaded getters somehow and throws the error of trying to initialize lazy loaded collection.

**Comment by chhsiao90** [comment]
I guessed the solution provided above skip the property, so the lazy loaded getters won't be called if it was configured correctly.

I can't see how your code and how you configured modelmapper, I'm not sure how I can help to fix this problem. Maybe you can write a minimum reproducible code for this?

**Comment by elibus** [comment]
I confirm the solution does not work for me either. It looks like the condition is called after the attempt to initialize the lazy loaded property.

**Comment by elibus** [comment]
I debugged a bit and it looks to me the conditions are applied after `resolveSourceValue` call.

```java
    Object source = resolveSourceValue(context, mapping);
    MappingContextImpl<Object, Object> propertyContext = propertyContextFor(context, source,
        mappingImpl);

    Condition<Object, Object> condition = (Condition<Object, Object>) Objects.firstNonNull(
        mapping.getCondition(),
        context.getTypeMap().getPropertyCondition(),
        configuration.getPropertyCondition());
    if (condition != null) {
      boolean conditionIsTrue = condition.applies(propertyContext);
      if (conditionIsTrue && mapping.isSkipped()) // when(condition).skip()
        return;
      else if (!conditionIsTrue && !mapping.isSkipped()) { // when(condition)
        context.shadePath(propertyPath);
        return;
      }
    }
```

`resolveSourceValue` calls this:

```
source = accessor.getValue(source);
```

which is triggering the error:
```
021-05-17T02:04:28,555+02  INFO 13242  [http-nio-8080-exec-2] e.i.e.RestResponseEntityExceptionHandler : Return 400: org.hibernate.LazyInitializationException: could not initialize proxy [com.test.User#2] - no Session
        at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:170) ~[hibernate-core-5.4.30.Final.jar:5.4.30.Final]
        at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:310) ~[hibernate-core-5.4.30.Final.jar:5.4.30.Final]
        at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45) ~[hibernate-core-5.4.30.Final.jar:5.4.30.Final]
        at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95) ~[hibernate-core-5.4.30.Final.jar:5.4.30.Final]
        at com.test.User$HibernateProxy$lawZxnDf.getCreateTimestamp(Unknown Source) ~[main/:?]
        ... suppressed 4 lines
        at org.modelmapper.internal.PropertyInfoImpl$MethodAccessor.getValue(PropertyInfoImpl.java:101) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.resolveSourceValue(MappingEngineImpl.java:197) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:170) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:105) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:71) ~[modelmapper-2.4.3.jar:?]
        ... 141 more
Wrapped by: java.lang.reflect.InvocationTargetException
        ... suppressed 4 lines
        at org.modelmapper.internal.PropertyInfoImpl$MethodAccessor.getValue(PropertyInfoImpl.java:101) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.resolveSourceValue(MappingEngineImpl.java:197) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.propertyMap(MappingEngineImpl.java:170) ~[modelmapper-2.4.3.jar:?]
        at org.modelmapper.internal.MappingEngineImpl.typeMap(MappingEngineImpl.java:151) ~[modelmapper-2.4.3.jar:?]
```

Am I missing anything?
